### ISSUE TITLE
sub-block/nested content will not save or allow any saving after incorrect or missing data fixed

### ISSUE THREAD

**Issue by Slipoch** [umbraco/Umbraco-CMS#10255]
A brief description of the issue goes here.

When a sub-block of a block or an item in nested content inside a grid element has a mandatory field, if the sub-block has mandatory or validated data, you can try to save, you will get the warnings, however after this, when you correct the failing fields, it doesn't allow saving.

## Umbraco version

I am seeing this issue on Umbraco version: 8.12

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

When a sub-block of a block or a item in nested content inside a grid element has a mandatory field (usually occurs within a block inside a block), if the sub-block has mandatory or validated data, you can try to save, you will get the warnings, however after this, when you correct the failing fields, it doesn't allow saving (sits on infinite loop, various JS errors may occur), or it will appear to give the same validation errors.

### Specifics

Chrome, Firefox, Safari tested
Umbraco version  8.12.0

### Steps to reproduce

 - Create a grid item or block that uses a blocklist where the sub-blocks have mandatory data (like title/image etc.), 
 - Save an incomplete sub-block, you will get a warning come up and the save will not proceed (correct)
 - Correct the data (like add a title) and hit save again, it will not save.

### Expected result

Updated data to be saved.
Message to show it has saved.

### Actual result
**first save** (without all data) shows the visual error mesaages (this property is invalid on outer list, value cannot be empty on inner item). JS also throws an error:
`TypeError: err is undefined
    submit http://localhost:65101/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js?cdv=447058392:300`

**Corrected save** same js error is thrown as above, inner item is still outlined in red however field message and outline have now vanished. outer item Still says this property is invalid. Save button leaves the busy symbol on it until you close out of the outer item.

Image below is second save, I tested using only the Title field
![image](https://user-images.githubusercontent.com/11207625/117606627-a28c0800-b19d-11eb-8299-f93a9b473d9b.png)

**Comment by nul800sebastiaan** [comment]
This should be fixed with the fixes in https://github.com/umbraco/Umbraco-CMS/issues/8954 and I will close this for now as fixed in 8.14. We covered all the nested (sub-sub-sub-etc item) validation in that one.

However, I am a little bit unsure how to set up the scenario that you have so if you could test it out that would be super helpful! A build of 8.14 that's almost the final one that we want to release is available here: https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=63328&view=artifacts&pathAsName=false&type=publishedArtifacts

Any testing you might be able to do with your real-life scenario would be absolutely great @Slipoch 👍

**Comment by donsrle** [comment]
Hi @nul800sebastiaan,
I am using grid editor with component whose one of the properties is of nested content data type and I still have issue like this one. After initial validation when mandatory fields within nested content are not provided I am seeing error above invalid fields within NC property (in my case Caption) and general error message above NC property (in my case Items) which is fine. After I provide text in Caption filed the error message above Caption is cleared but the one above Items is still present so I am not able to submit. Even though I remove this 'test' item the error message "This property is invalid" above Items field is still present and therefore not able to submit it neither.
![dtge-nested](https://user-images.githubusercontent.com/2004969/121695367-4a616200-cacb-11eb-8847-18f8d0dac1aa.png)
I am not sure if this is related to DTGE or NestedContent but it is similar as in this issue.
Thanks in advance,
Srdjan
