### ISSUE TITLE
Multi URL Picker Isn't working at all

### ISSUE THREAD

**Issue by DavidArmitage** [umbraco/Umbraco-CMS#10479]
### Which Umbraco version are you using?

Umbraco version 9.0.0-beta003

### Bug summary

The Multi Url Picker is not working at all.
I tested directly on a page, and within site block lists.

### Specifics

You add a Multi URL Picket to the page.
Add a url to the page content using the data type.
Save the node (this appears to work ok)
But when you come back to the page the Multi URL Picket is null and there is an onscreen error popup.

I created video of this here.
https://www.awesomescreenshot.com/video/4145715?key=51e5f9c8600d1ff8d175327e1fba55b2

### Steps to reproduce

You add a Multi URL Picket to the page.
Add a url to the page content using the data type.
Save the node (this appears to work ok)
But when you come back to the page the Multi URL Picket is null and there is an onscreen error popup.

### Expected result / actual result

The link should save and retain the data.

**Comment by bergmania** [comment]
Thanks, I can reproduce.. Seems like a merge from v8 that has gode wrong.. Ill fix up

**Comment by bergmania** [comment]
Fixed by this commit https://github.com/umbraco/Umbraco-CMS/commit/5eb94736578b4efe0fccfa8890283ce66d2fd0cc

**Comment by jannikanker** [comment]
@bergmania we're still seeing this behavior in 9.0.0-rc001 :-(

**Comment by jannikanker** [comment]
Oh, whoops, looks like it's being handled in https://github.com/umbraco/Umbraco-CMS/issues/10694 .
