### ISSUE TITLE
Block item radio list property set to mandatory shows red required message on save, even when value is chosen

### ISSUE THREAD

**Issue by argentini** [umbraco/Umbraco-CMS#11882]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.2.0

### Bug summary

Block item mandatory radio list property always shows red required error message on save regardless of whether a value is chosen or not

### Steps to reproduce

see description

### Expected result / actual result

Should validate if a value is chosen

**Comment by kjac** [comment]
Hi @argentini,

Thank you for reporting this and sorry for the late response. 

This issue seems to have been fixed in version 10 - here's a screencast from version 10.3.2:

![11882](https://user-images.githubusercontent.com/7405322/211250966-0e3a9b9e-f8c9-4b66-9d99-e3254ecfea59.gif)

**Comment by argentini** [comment]
This is still happening occasionally in version 11. It may be related to making changes to doc types then trying to save an existing content item that uses that doc type.
