### ISSUE TITLE
UMB-XSRF-V not being marked secure when global usehttps is set to true

### ISSUE THREAD

**Issue by neo-cphilipp** [umbraco/Umbraco-CMS#12285]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0

### Bug summary

When the "Global:UseHttps" setting is set to true in the appsettings.json, all the Cookies will be labeled secure except UMB-XSRF-V cookie.  This cookie should be marked secure when usehttps is set to true.

### Specifics

Once a user is logged into to the backoffice, there will be a cookie that can be seen in the browser cookie list called UMB-XSRF-V:
![image](https://user-images.githubusercontent.com/26909403/164548307-a070ae01-9c81-4768-9e87-eb32844b2295.png)

From what I can tell from the documentation adding the following to the appsettings.json will add secure to all the application cookies:

```json
"Umbraco": {
    "CMS": {
      "Global": {
         "UseHttps": true
      }
   }
}
```

However, when that setting is updated in the appsettings.json all the cookies but the UMB-XSRF-V cookie is labeled secure.  This one should not be left without the secure tag.  

### Steps to reproduce

Once a user is logged into  the back office the cookie can be seen in the browsers list of application cookies.  I am using Chrome as a browser.

### Expected result / actual result

The UMB-XSRF-V should be marked secure and it is not marked secure.

**Comment by mikecp** [comment]
Solved by PR 12286

**Comment by shearer3000** [comment]
hi - this issue can still be observed in umbraco 10.x

**Comment by shearer3000** [comment]
also still an issue on the latest, 12.2 at the time of writing:
![image](https://github.com/umbraco/Umbraco-CMS/assets/2433680/0b0a7fe9-73c0-457c-854b-01d1b5e17af0)
