### ISSUE TITLE
Hierarchy  URL in RTL language is not working properly

### ISSUE THREAD

**Issue by ebadola** [umbraco/Umbraco-CMS#12621]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

all version

### Bug summary

Hi
In RTL Language URL segment order is incorrect

below image is my structure
![Untitled](https://user-images.githubusercontent.com/11830903/175779165-3d4a6035-59ab-48a8-a006-8219d8ec100e.jpg)

result URL is this

![Capture](https://user-images.githubusercontent.com/11830903/175779198-605ed048-501c-46ec-a60d-facc63dc0894.png)

but URL suppose to be in hierarchical order

![Capture](https://user-images.githubusercontent.com/11830903/175779205-3e7f6020-1760-4b6e-ad65-891c2e8feeba.jpg)

how can I fix the problem? 

### Steps to reproduce

![Capture](https://user-images.githubusercontent.com/11830903/175779205-3e7f6020-1760-4b6e-ad65-891c2e8feeba.jpg)

**Comment by bjarnef** [comment]
I know about RTL languages and the part of the backoffice support this, but I didn't know it also applied to the URL structure.

What you could try is looking at implementing a custom Url Segment Provider inheriting `IUrlSegmentProvider` : [Url Segment Provider](https://our.umbraco.com/documentation/reference/routing/request-pipeline/outbound-pipeline#url-segment-provider)

maybe reverse the segments if `culture` match a specific ISO code.

or you could try is looking at implementing a custom Url Provide inheriting `DefaultUrlProvider
[Custom Url Provider](https://our.umbraco.com/documentation/reference/routing/request-pipeline/outbound-pipeline#custom-url-provider)

**Comment by bergmania** [comment]
Hi @ebadola..

Thanks for letting us know.. 

In cases where the domain and culture is set up so something like `/relative` for a culture that is RTL. Do you expect that part to be added as the right-most URL segment, or would that part be considered part of the domain?

**Comment by ebadola** [comment]
It should be like this

`
(http/https)://domain/culture/mainpage/subpage1/subpage2/....
`

or in RTL Languages

`
 @(http/https)://domain/culture/زیر-صفحه-2/زیر-صفحه-1/صفحه-اصلی/...
`

I don't know if I did respond properly

I hope this is a useful respond

**Comment by bergmania** [comment]
Thanks ebadola.. 

That's was lucky, because otherwise it would have been very hard to archive with our current UI.  I'll look into it :)

**Comment by Zeegaan** [comment]
Hey @ebadola this is now fixed in https://github.com/umbraco/Umbraco-CMS/pull/12635, thanks for your report! 🐛

**Comment by ebadola** [comment]
Hi Again
Problem still exists

![image](https://user-images.githubusercontent.com/11830903/183026668-712a4916-a952-4d55-8b53-8c64d3409011.png)


as you can see in the picture 
in the footer breadcrumb, the Hierarchy  is in the correct  order, 
and the URL also should be in exact order

**Comment by bergmania** [comment]
Hi @ebadola .. 

Did you set the new setting?
> Set the new Umbraco:CMS:Global:ForceCombineUrlPathLeftToRight setting to false

This setting was introduced to avoid breaking changes

**Comment by ebadola** [comment]
> Hi @ebadola ..
> 
> Did you set the new setting?
> 
> > Set the new Umbraco:CMS:Global:ForceCombineUrlPathLeftToRight setting to false
> 
> This setting was introduced to avoid breaking changes

Thanks, It worked
