### ISSUE TITLE
Backoffice UI errors when cancelling creating/saving/deleting notifications

### ISSUE THREAD

**Issue by ronaldbarendse** [umbraco/Umbraco-CMS#12636]
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

10.0.0

### Bug summary

The backoffice UI contains UI errors when the creating, saving or deleting notifications are cancelled for:
- Document types
  - Showing both success and error message when saving:
    ![Document types saving](https://user-images.githubusercontent.com/1051287/176388362-310fd562-25cb-49ba-8100-f37482b2d4ba.png)
  - No message when deleting, item removed from tree, but refreshing the tree shows it again
- Media types (showing both success and error)
  - Showing both success and error message when saving:
    ![Media types saving](https://user-images.githubusercontent.com/1051287/176388551-1441e2ea-45b0-457c-80af-049fe34deeae.png)
  - No message when deleting, item removed from tree, but refreshing the tree shows it again
- Member types
  - Showing both success and error message when saving:
    ![Member types saving](https://user-images.githubusercontent.com/1051287/176388667-98050955-756f-474a-ae69-24560427bc59.png)
  - No message when deleting, item removed from tree, but refreshing the tree shows it again
- Data types
  - Showing both success and error message when saving:
    ![Data types saving](https://user-images.githubusercontent.com/1051287/176388739-40ac0401-5504-485b-ad46-fab857c26b18.png)
  - No message when deleting, item removed from tree, but refreshing the tree shows it again
- Templates
  - Showing only success message when saving (even though it's not saving changes):
    ![Templates saving](https://user-images.githubusercontent.com/1051287/176388856-96231263-200d-4dd0-9ec8-d73e7307f324.png)
  - No message when deleting, item removed from tree, but refreshing the tree shows it again
- Partial views
  - Showing both success and error messages (including additional ones for trying to create the physical file and fetching the file contents) when creating:
    ![Partial views creating](https://user-images.githubusercontent.com/1051287/176391643-02e49fcf-e06c-4160-8860-72a0a8b46a4e.png)
  - Showing both success and error messages (including an additional one for trying to save the physical file) when saving:
    ![Partial views saving](https://user-images.githubusercontent.com/1051287/176389956-0e211874-8136-4f4d-b228-239ebb458922.png)
  - 404 error when deleting. broken dialog:
    ![Partial views dialog deleting](https://user-images.githubusercontent.com/1051287/176390523-d437e0f2-1bbe-4856-9786-d509d90a8c7f.png)
    ![Partial views deleting](https://user-images.githubusercontent.com/1051287/176390300-239dd5cd-b3b4-4420-bb47-4292a6153628.png)

### Steps to reproduce

These errors can be easily reproduced by adding the following code into your Umbraco project that cancels all above mentioned notifications:

```c#
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;

public class ApplicationComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<ContentTypeSavingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<ContentTypeDeletingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<MediaTypeSavingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<MediaTypeDeletingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<MemberTypeSavingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<MemberTypeDeletingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<DataTypeSavingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<DataTypeDeletingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<TemplateSavingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<TemplateDeletingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<PartialViewCreatingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<PartialViewSavingNotification, ApplicationNotificationHandler>();
        builder.AddNotificationHandler<PartialViewDeletingNotification, ApplicationNotificationHandler>();
    }

    private class ApplicationNotificationHandler :
        INotificationHandler<ContentTypeSavingNotification>,
        INotificationHandler<ContentTypeDeletingNotification>,
        INotificationHandler<MediaTypeSavingNotification>,
        INotificationHandler<MediaTypeDeletingNotification>,
        INotificationHandler<MemberTypeSavingNotification>,
        INotificationHandler<MemberTypeDeletingNotification>,
        INotificationHandler<DataTypeSavingNotification>,
        INotificationHandler<DataTypeDeletingNotification>,
        INotificationHandler<TemplateSavingNotification>,
        INotificationHandler<TemplateDeletingNotification>,
        INotificationHandler<PartialViewCreatingNotification>,
        INotificationHandler<PartialViewSavingNotification>,
        INotificationHandler<PartialViewDeletingNotification>
    {
        private readonly EventMessage _cancelEventMessage = new EventMessage(
            "This operation has been cancelled",
            "You should only see this error message.",
            EventMessageType.Error);

        public void Handle(ContentTypeSavingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(ContentTypeDeletingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(MediaTypeSavingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(MediaTypeDeletingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(MemberTypeSavingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(MemberTypeDeletingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(DataTypeSavingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(DataTypeDeletingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(TemplateSavingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(TemplateDeletingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(PartialViewCreatingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(PartialViewSavingNotification notification) => notification.CancelOperation(_cancelEventMessage);
        public void Handle(PartialViewDeletingNotification notification) => notification.CancelOperation(_cancelEventMessage);
    }
}
```

### Expected result / actual result

I would expect to only see the single error message from the notification handler when trying to create, save or delete the different items and in addition to that:
- Show a cross in the save button, instead of a checkmark (indicating the operation did not succeed);
- Keep the item in the tree.

**Comment by DanDiplo** [comment]
I'm seeing a similar issue in 10.0.1 when trying to cancel a Notification. I have code similar to this:

```
public class OnContentUnpublishing : INotificationHandler<ContentUnpublishingNotification>
    {
        public void Handle(ContentUnpublishingNotification notification)
        {
            foreach (var node in notification.UnpublishedEntities)
            {
                if (NotificationSettings.ShouldNotBeDeleted(node))
                {
                    notification.CancelOperation(new EventMessage("Warning!", $"The page '{node.Name}' ({node.Id}) has been set so it cannot be unpublished.", EventMessageType.Error));
                    notification.Cancel = true;
                }
            }
        }
    }
```
When I try and unpublish a page where the Notification is set to be cancelled then it runs, but only *after* the normal "this page has been published" has already run. So it displays the "success" notification, then it shows my "cancel" notification - and the page isn't prevented from being unpublished. 

![image](https://user-images.githubusercontent.com/6676168/181830126-b2f20292-a479-47c9-bfb7-fbb0fcf1d9be.png)

I expect and want the publication to be stopped and it only show my error message.

**Comment by Zeegaan** [comment]
I can indeed reproduce this, and agree, no success message should be shown if cancelled 🤔 Marking this up for grabs as we'd love some help with this! 💪

**Comment by matthewcare** [comment]
Hi @Zeegaan 
I found this issue as well and was going to take a look.
The problem stems from `ContentTypeController.cs:469` whereby a success notification is always added to the response.

At this stage there is no way to know if a notification handler has caused a "cancel" since the underlying save event returns void.
The easiest way to resolve this would be to check if a message has been added of type `Error`
`display.Notifications.Any(x => x.NotificationType == NotificationStyle.Error)`
and then not adding the success notification in that case.

Or perhaps checking if the number of user defined messages is more than 1?

Either way, this will result in a change of behaviour which is going to have to be decided by someone, and with the work that is being done for v13/14 making large changes to do it "properly" is likely not worthwhile.

Thanks,
Matthew

**Comment by jdpnielsen** [comment]
> and with the work that is being done for v13/14 making large changes to do it "properly" is likely not worthwhile.

Where can i find more information about what's happening with this in v13/14?

**Comment by matthewcare** [comment]
@jdpnielsen 
There are a few places where discussion is taking place, but for the most part following along with the roadmap
https://umbraco.com/products/knowledge-center/roadmap/
specific for the new backoffice though, there is this blog post
https://umbraco.com/blog/bellissima-preview-releases-of-the-new-backoffice/

**Comment by jdpnielsen** [comment]
@jdpnielsen Ah, just in general regarding Bellissima. Thought there were ongoing discussions regarding publishing/notifications specifically.

**Comment by matthewcare** [comment]
Hi @Zeegaan 

I see a few other issues being opened with this same problem.
Did you have any suggestions from my findings?

Thanks,
Matthew

**Comment by Zeegaan** [comment]
@matthewcare As it is potato holiday this week 🥔 I will bring this up with the team on Monday and discuss how to go about it 😁

**Comment by matthewcare** [comment]
@Zeegaan Have all of the potatoes been eaten?

**Comment by Zeegaan** [comment]
@matthewcare It will be looked at for v14 behavior👍 
I think your suggestion could be done for V13, so if you're up for making a PR for v13 that would be great 😁

**Comment by Attackmonkey** [comment]
There's a bunch of other places this occurs as well. For example, if you cancel a member save, you get a success and a cancel message. If you you cancel a member delete, you just get a success message, the custom message you set never gets shown to the user.

**Comment by jdpnielsen** [comment]
For v14 it might be nice to look into moving this from a long running post request to using websockets/signals or similar to stream notifications/messages to the ui.

**Comment by PotatoDotJar** [comment]
Having a similar issue when cancelling a `ContentCopyingNotification` or a `ContentMovingNotification`.

For `ContentCopyingNotification`, the UI freezes up due to a JS error:
![image](https://github.com/umbraco/Umbraco-CMS/assets/7833468/2f122348-8a19-4fa2-8495-5287d097e06f)
![image](https://github.com/umbraco/Umbraco-CMS/assets/7833468/46980efc-c325-4267-b217-5fd296b0ac67)
The POST: PostCopy returns `null`

For `ContentMovingNotification`, the UI shows a success message even though the operation was cancelled. Looking at the BO content, no content was moved despite the success message in the UI.

**Comment by OwainWilliams** [comment]
Just ran in to this issue on V16 where I have a "ContentSavingNotification" and 

```
notification.Cancel = true;
notification.Messages.Add(new EventMessage(
				"Content Creation Restricted",
				"X can only be added to X when the X is at the Primary level.",
				EventMessageType.Error));
```

<img width="451" height="313" alt="Image" src="https://github.com/user-attachments/assets/77c6d9b3-8745-4adb-8b96-285e154f69b1" />

Ideally, I just want the notification message I set and not the Umbraco error.

**Comment by jawood1** [comment]
I'm also seeing this issue on v17.1 as well along with a single document event message returning your event message + the generic error occurred notification with a bulk saving/publishing event the custom event message isn't returned at all and just a generic bulk validation error message is returned.

**Comment by kurttegerero** [comment]
I'm also experiencing this issue in v16, where I added a custom error message, but the default error message keeps appearing.

`notification.CancelOperation(new EventMessage("Rename Not Allowed", $"Renaming content node '{original.Name}' is not allowed.", EventMessageType.Error));`

<img width="561" height="400" alt="Image" src="https://github.com/user-attachments/assets/e622e4bd-24d6-40bd-84c7-e30e466c6840" />

**Comment by AndyButland** [comment]
This one is fixed by https://github.com/umbraco/Umbraco-CMS/pull/21993 for 17.3.

**Comment by orangejuice-bram** [comment]
@AndyButland I am still experiencing this issue in v17.3.0 on Umbraco Cloud. I've added a DictionaryItemSavingNotification and get the following when I cancel the operation:

<img width="467" height="283" alt="Image" src="https://github.com/user-attachments/assets/c19538a4-6793-4b69-a1c3-5b056e9c841d" />

using:

```
notification.CancelOperation(new EventMessage(
                    "Forbidden", "It is not allowed to change the key of a dictionary item because this will break any usage of the item.", EventMessageType.Error));```

**Comment by AndyButland** [comment]
I've just tested with the following @orangejuice-bram - on 17.latest - and it seems OK for me:

```
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Notifications;

namespace Umbraco.Cms.Web.UI.Custom.NotificationHandlers;

public class CancelDictionaryItemSavingHandler : INotificationHandler<DictionaryItemSavingNotification>
{
    public void Handle(DictionaryItemSavingNotification notification)
    {
        if (notification.SavedEntities.Any(item => item.ItemKey.StartsWith("x", StringComparison.OrdinalIgnoreCase)))
        {
            notification.CancelOperation(new EventMessage(
                "Dictionary Item Save",
                "Dictionary item keys starting with 'x' are not allowed (test handler).",
                EventMessageType.Error));
        }
    }
}
```

I just see the one message as expected.

Suggest if you are still having trouble on the latest release to create a new issue, sharing your full code for replicating the issue.
