### ISSUE TITLE
Saving existing document types is very slow using Umbraco 10

### ISSUE THREAD

**Issue by teeto** [umbraco/Umbraco-CMS#13080]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.1

### Bug summary

Create a document type, save.
Edit the document type save again.
It gets saving for about 1-3 minutes, sometimes more, without errors 

### Specifics

I dont use Models builder, i have set it to Nothing, but i have tried other values.
No errors on screen neither console javascript errors.
This is my Umbraco config:
`"Umbraco": {
    "CMS": {
      "Runtime": {
        "Mode": "Development"
      },
      "ModelsBuilder": {
        "ModelsMode": "Nothing"
      },
      "Global": {
        "UseHttps": false
      },
      "Content": {
        "MacroErrors": "Throw"
      },
      "Hosting": {
        "Debug": true
      },
      "RuntimeMinification": {
        "UseInMemoryCache": true,
        "CacheBuster": "Timestamp"
      }
    }
  }`

### Steps to reproduce

My OS is Windows 10 Pro
Install lastest visual studio umbraco templates
Create new umbraco project using the last version (10.2.1)
Select sql server database, my version is SQL Server 14
Create a document type, save.
Edit the document type save again.
It gets saving for about 1-3 minutes without errors 

### Expected result / actual result

Save the document type in 2-3 seconds, as when creating it.

**Comment by nzdev** [comment]
Solved by https://github.com/umbraco/Umbraco-CMS/pull/12278

**Comment by JamesShelley** [comment]
Have also been consistently reproducing this across an ongoing Umbraco 10 build, and it has been making the development experience quite frustrating. Will check back through logs to see if I can provide any useful information to help out!

**Comment by OwainWilliams** [comment]
Hi, 
I had a similar issue and I found that my laptop memory usage was hitting >92% and my local instance of Umbraco 10 would run really slowly until I could get the memory usage back down below 90%. This usually meant I had to close Visual Studio. 

Can you check the memory usage the next time you have this issue?

**Comment by teeto** [comment]
It seems to happen only on development mode, in production it works fine.
I dont think it is a memory issue, i guess it is related to models builder that while set to "Nothing" may be it is doing something in the background which may be rebooting the app.
I opened this issue in Umbraco v8 that was a very similar issue:
https://github.com/umbraco/Umbraco-CMS/issues/7756

**Comment by solarpolar** [comment]
Also having this very frustrating developer experience with v10. Anyone else?

**Comment by nikolajlauridsen** [comment]
Hey folks, I've been having a look at trying to reproduce this issue, but unfortunately without success, so I've made a little video where I go through it, I'd love to hear if I'm missing something.

It's also worth mentioning that the PR that nzdev mentioned was released with 10.3, so maybe it'll help if you upgrade to the newest version (10.3.2). 

Hope to hear from you 

https://user-images.githubusercontent.com/16456704/206185423-cbe84dae-2457-47c4-b585-1bd866e2d07c.mp4

**Comment by nzdev** [comment]
@nikolajlauridsen I suspect this wont be apparent till you have many existing documents of that type.

**Comment by nikolajlauridsen** [comment]
Hey Chad, thanks for the swift response 😄 I got a bit confused since it was mentioned that this happens without having a lot of content.

I tried again, this time with 2k content nodes (looking like the screenshot bellow), this time it did indeed take a little longer, but only 1.68 seconds, which is still far from the minutes otherwise reported. So I'm wondering is something else is afoot here? Other than NuCache having to do some rebuilding (By the way, big H5YR for your improvements in this area 🎉)

![image](https://user-images.githubusercontent.com/16456704/206194717-aa8a7fd2-ded4-46e1-a583-c3c85203ea5f.png)

**Comment by nzdev** [comment]
Thanks @nikolajlauridsen . For reference, I have a site with ~200k nodes of one type. The time scales with the number of nodes of the type.

**Comment by nzdev** [comment]
I'd recommend using SQL profiler to see what SQL statements run during doc type saving to get more detail on what to optimize.

**Comment by nikolajlauridsen** [comment]
Yeah, I can see how that'll add up in the end, but I guess in that case, there's not really a silver-bullet fix for the issue other than making NuCache faster, or replacing it (which is on the roadmap).

But regardless I'll bring it up with the team at our next meeting, just to get their input, but I'm afraid that any major NuCache improvements are not really in the cards right now, with Delivery API, EF Core, and new back office being the major projects being worked on right now, if only there were more hours in the day. 

But let's see what the team says.

**Comment by nzdev** [comment]
Thanks @nikolajlauridsen. I've done what I can (including a few prs to help with replacing / optimizing how nucache works that were not merged https://github.com/umbraco/Umbraco-CMS/pull/9857). For my vote, I'd take a fix for NuCaches scaling  problems any day over replacing NPoco with EFCore given the major problems with NuCache. Given NPoco isn't broken and there isn't really anything fundamentally wrong with it, EFCore is more of a nice to have (and I'm a fan of EF https://github.com/nzdev/Umbraco-CMS/commits/v9/efcore).

**Comment by dawoe** [comment]
I am on the same page as @nzdev here.

I think the caching layer should be fixed in favor of EF Core. Caching issues are already affecting a lot of websites. 

Dave

**Comment by teeto** [comment]
Thanks @nikolajlauridsen  for your help. 
As i was experiencing the problem, it was happening only in my local machine, an Umbraco installation with very little content amount. Once published to production everything is fine. So i though it had to be with the Runtime Mode = "Development". 
But recently i changed my the connection string to the server BD, and the problem is not happening, so it may be related to my local dev BD. 
I am using  Microsoft SQL Server Developer 15.0.2095.3, 64bit on Windows 10 Pro. 
Server collation as "Modern_Spanish_CI_AS". 
My connection string is this:
`Server=localhost;Database=MyDB;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=True;connect timeout=300;`
May be the Developer edition has some limitation that Umbraco is reaching when a modifing document type?

**Comment by teeto** [comment]
It still happens in Umbraco 11
I have installed a fresh new Umbraco 11 using VS new project and selecting Umbraco template.
On database i select custom and paste this string:
Server=localhost;Database=dbname;Trusted_Connection=True;MultipleActiveResultSets=True;
I am using Microsoft SQL Server Developer 15.0.2095.3, 64bit on Windows 10 Pro.
After umbracon installs i manage nuget packets and install:
WebEssentials.AspNetCore.OutputCaching
Umbraco.StorageProviders.AzureBlob

I create a "Default" template under settings.
Then create some document types, go to settings, create new folder "Web"
Then create some document types, i create them selecting create and then "Document type" (without template)
Create some properties and select "Default" template.

After creating one root content i start having problems editing the document types.

**Comment by Migaroez** [comment]
✅ Reproduded on v11 dev (11.5.0 - e6a1640) using SQL Server developer 16.0.1105.1 with the following [generation code](https://gist.githubusercontent.com/Migaroez/162faab59d4d04515d665e27f50e2735/raw/ccb883b815015798eb58912a7d008323bdbf0e39/ContentGenerateController) and the following payload
```
{
    "amount":30000,
    "doctypeAliases":["invariantDoctype"],
    "containingDoctypeAlias":"container",
    "containtingDoctypeUsesListview" : "true",
    "newDocTypePropertyMinAmount":20,
    "newDocTypePropertyMaxAmount":20,
    "languageIsoCodes":["en-us"]
}
```
Adding a property to this doctype (simple textstring) and hitting save, it took 5.4 minutes for the server to respond on the PostSave

**Comment by AndyButland** [comment]
Although old, we'll keep this open as there may be more to do to optimise these situations where a lot of documents are linked to a changed document type.

However the are some optimisations in play now:

- https://github.com/umbraco/Umbraco-CMS/pull/21910 - has some optimisation in the rebuild, but more importantly now only rebuilds when we really need to (so not on innocuous changes like icons and descriptions, and not on typical feature development flow where properties are only being added). It rebuilds now only when properties are renamed/removed, variation is changed, compositions are removed.  This has been backported and released for Umbraco 13.
- https://github.com/umbraco/Umbraco-CMS/pull/22194 - allows the option to move the rebuild into a background task, so the work remains, but it's not happening whilst the save document type process is completing (either via the backoffice UI, or a deployment tool action).
