### ISSUE TITLE
EnsureCaches in PublishedSnapshotService is deadly for large websites

### ISSUE THREAD

**Issue by LennardF1989** [umbraco/Umbraco-CMS#13525]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

Anything since v8, maybe even older.

### Bug summary

In follow up to my previous issue about Lucene indexes rebuilding on startup (#13498) - we ran into another issue last weekend in regards to NuCache.

This particular website has 21480 content nodes (each with over 5 variants) and 166193 media nodes, so quite a lot data. This is an Umbraco v8.17, however this issue is technically still an issue in v11 right now (See link below).

Over the weekend, our website decided to cold boot in a busy period, triggering a rebuild of NuCache.content.db and NuCache.media.db. In particular, this line of code: https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.PublishedCache.NuCache/PublishedSnapshotService.cs#L542

Rebuilding these caches take about 1 minute for content, but about 20 minutes for media. During this time, the website is effectively offline because it locks all requests until this process is done. If at the same time a lot of requests are coming in and get locked, IIS will at some point get into a panic mode and restart the AppPool while the application is still hard at work booting itself.  So you pretty much end up in an infinite loop where the website never gets the chance to boot properly, because it gets killed prematurely. Either something is very wrong with the media cache building, or it just takes as long as it does (for the record: this is a separate DB server with a lot of CPU and RAM), concluding that Umbraco is not suited for handling this amount of nodes/data.

Anyway, the only fix is starting the website on a different AppPool only we can access and kick off the process with a single request and just wait it out, then swap the AppPool back to the original and hope it will load the NuCache files.

We have hacked the PublishedContentService to always make Umbraco think it's warm booting (for the record: only the PublishedContentService gets the fake SyncBootStateAccessor), so it won't attempt to rebuild existing cache files (only if they are somehow corrupted or missing), but this is far from an ideal situation and it doesn't fix the issue of preventing the site to start for over 20 minutes if it has to for whatever reason.

### Steps to reproduce

We are more than happy to provide a DB dump of this website to a representative of Umbraco in private and under terms for further investigation.

Or you can replicate the above numbers by just generating content/media. Make sure each content paga has 5 languages as well as quite some variant properties (including blocklists).

### Expected result / actual result

- A different method of rebuilding these cache files, or at least look into speeding things up.
- A toggle in the configuration to force Umbraco to just load the NuCache files if they exist, regardless of Cold Boot/Warm Boot.

---
_This item has been added to our backlog [AB#24783](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/24783)_

**Comment by nikolajlauridsen** [comment]
Hey @LennardF1989, unfortunately with NuCache, a site of that side will always take a long time to cold-boot, so I'm afraid there's not much we can do about that, other than replacing NuCache (Which is [on our roadmap](https://umbraco.com/products/roadmap/)).

I am quite interested in why your site decides to cold boot since that shouldn't really just happen randomly, and should be quite rare. 

Is there anything in your logs indicating why your site decides to cold-boot? Instead of warm booting?

**Comment by LennardF1989** [comment]
The cause of the the cold boot was that a huge influx exceptions triggered a panic reaction in IIS. So our current hack fixes that issue by not rebuilding during a cold boot. @nikolajlauridsen

**Comment by LennardF1989** [comment]
A long boot time for an enterprise level application like this is unacceptable to the point where the client will second-guess if Umbraco was a good choice at all, in turn also reflecting badly on us. I would highly consider moving this roadmap item to somewhere earlier, rather than "Later".

I would like to see a feature flag to disable building the NuCache files on startup without hacks (even when corrupt, instead throw an exception) and exposed functions to validate the correctness of the caches. We already rebuild all caches and indexes in a nightly job, so we can postpone the pain a bit if we have more control over the process without having the Reflect our way into everything.

**Comment by nikolajlauridsen** [comment]
I'll take it up with the team at HQ, to see what we can do, I do think your request with a feature flag is reasonable, so we'll see how we can move forward on this.

**Comment by LennardF1989** [comment]
> I'll take it up with the team at HQ, to see what we can do, I do think your request with a feature flag is reasonable, so we'll see how we can move forward on this.
Any word on when this could be expected to be part of a sprint? Our "hack" works, but would like to have an official solution.

**Comment by PerplexDaniel** [comment]
@LennardF1989 @nikolajlauridsen We also run in to this issue in one of our v8 sites (8.17.1) that has a lot of content nodes (120K+). Rebuilding the NuCache takes around 10 minutes if I take the prod db locally, in production it apparently has issues to complete at all.

I had a look in the Umbraco source code and it looks like the culprit of all of this is an extremely slow `.QueryPaged` queries that are being done to fetch all content/media ([here for v8](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/PublishedCache/NuCache/DataSource/DatabaseDataSource.cs#L238) and still present [in 10.5.1 here](https://github.com/umbraco/Umbraco-CMS/blob/release-10.5.1/src/Umbraco.PublishedCache.NuCache/Persistence/NuCacheContentRepository.cs#L236)). Note it is done in a couple of different methods in that class for both content and media, it's all the `QueryPaged` calls.

For a local test I replaced the `QueryPaged<>` methods with `Fetch<>` and then I was able to rebuild the files (NuCache.Content.db + NuCache.Media.db) in 10 **seconds** rather than 10 **minutes** (see [this commit in my fork](https://github.com/PerplexDaniel/Umbraco-CMS/commit/16be331c58fc7c49a3f03cebce308113acb1b309)). So I would stress HQ to have a look at this because it seems this QueryPaged method is extremely slow and more importantly it does not actually seem needed, loading everything using Fetch is extremely fast and I did not notice any extreme memory usage, although I did not do an detailed comparison in memory usage. I was mainly interested in the rebuild time and I would much rather use more memory rather than have my website be effectively offline for 10 minutes (or not boot anymore at all).

If you do not want to change it to Fetch for everyone, at least consider making this an option. In v10 it can be done using [`NuCacheSettings`](https://github.com/umbraco/Umbraco-CMS/blob/release-10.5.1/src/Umbraco.Core/Configuration/Models/NuCacheSettings.cs), in v8 we could add some Web.config appSetting to disable paged queries and use fetch instead.

**Comment by LennardF1989** [comment]
@PerplexDaniel This one fell under the radar for me, but did you ever end up proposing this as a PR to HQ? I reckon this would be a perfectly fine solution as an opt-in for v8 websites, that will not get the benefit of the lazy loaded NuCache the newer version will get.

**Comment by PerplexDaniel** [comment]
@LennardF1989 No, I expected @nikolajlauridsen to have a look at this and reply or discuss with HQ first. We now run a custom build of 8.17.1 that includes my change on our production website without issues so far so we are happy but it would definitely be good to include this in Umbraco itself since `QueryPaged` seems way too slow.

**Comment by bergmania** [comment]
Hi @PerplexDaniel.

Thanks for the notes and the commit in your fork.

This was originally introduced to avoid DB timeouts, but I guess the reason for those have been usage of Query instead of Fetch from NPoco. Obviously using fetch will lead to higher memory useable, but I agree performance is more important in this scenario. 

I like the idea about making this configurable. I'm wondering whether we should make an explicit configuration or introduce some kind of threshold to the pagesize, and fallback to execute all in one fetch.

**Comment by PerplexDaniel** [comment]
Hi @bergmania. 

In an ideal world I would just make it the new default and make paged queries an opt-in option considering it seems superior. However, considering this is a critical part of Umbraco and in case of errors websites do not boot at all it is probably best to just keep the existing paging in place and make the fetch an explicit opt-in option. That and the fact the `Fetch()` approach has not been tested much in the real world at all. Problem is not everyone will be aware and will keep the slow paged queries, but it is what it is. Not sure about basing it on page size, that will probably be unexpected for people. Better just to add a `UsePagedSqlQuery` or something similar and default it to `true`.

**Comment by bergmania** [comment]
@PerplexDaniel 

Fine with me with an explicit `UsePagedSqlQuery`.
I agree we cannot change the default in a minor, but we can consider to do it for v13.

**Comment by JeffreyPerplex** [comment]
Hi @bergmania ,

do you have any update perhaps on this issue? It's really annoying for us (or exactly our client) at this moment and the fix looks like a magic bullet that improves everyone's boot time of Umbraco dramatically! 

So sounds like a no-brainer?

Please let me know if there's anything we can do to make this happen soon :)!

Cheers, Jeffrey

**Comment by bergmania** [comment]
Hi @JeffreyPerplex..

Sorry I'm aware of this, but currently can't find time to move on it, a PR would be lovely, but as mentionen we need to make it backward compatible for minor releases.

I imaging it can happen using a configuration value for now, that we can implement so new projects start with the fetch and existing needs to opt-in to.

Sounds like this needs to be implemented for both v8, v10 and v12 🙈 (I would expect it to be easy to cherry pick between 10 and 12).

**Comment by andr317c** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/14827

**Comment by LennardF1989** [comment]
@andr317c While it fixes a part of the issue, the issue is technically not fixed before lazy loaded NuCache is out and about.

**Comment by nul800sebastiaan** [comment]
Linking https://github.com/umbraco/Umbraco-CMS/pull/14806 for the fix in v10 and 12.
