### ISSUE TITLE
PublishedElementExtensions Value<T> method throws NotImplementedException when using with IPublishedValueFallback

### ISSUE THREAD

**Issue by zharonar** [umbraco/Umbraco-CMS#14202]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.5.1

### Bug summary

Hi, there is a strange exception after upgrading from 10.3.2 to 10.5.1.

**Quick code review:**

We have our BaseView that implements

```
private SEO? _seo;
public SEO SEO => _seo ??= Model is IPublishedContent content ? new SEO(content, new NoopPublishedValueFallback()) : throw new InvalidOperationException($"{nameof(T)} must implement IPublishedContent");
```

Which is derrived from SeoComposition, that is generated out of ModelBuilder.

**Possible bug**

In the interface `IPublishedValueFallback` there is property `IVariationContextAccessor VariationContextAccessor { get { throw new NotImplementedException(); } set { throw new NotImplementedException(); } }`

This property is used in `PublishedElementExtensions` method 
```
public static T? Value<T>(
this IPublishedElement content,
IPublishedValueFallback publishedValueFallback,
...
```

`EventuallyUpdateVariationContext(publishedValueFallback, culture, segment);`

**Since we can't see if this is anywhere implemented, obviously we get NotImplementedException, which obviously throws this property if called without proper implementation.**

I hope you can look into this issue, and that I explained properly what's the issue, and possible cause of the problem.

### Specifics

Possible cause? 
https://github.com/umbraco/Umbraco-CMS/commit/451d1cec6ab9ea3f1ea269fff3c4e95debfae5e7

### Steps to reproduce

**Our Issue:**

When we call on page SEO.MetaTitle it goes through the code... then we come up to the method in generated composer

```
/// <summary>Static getter for Meta-Titel</summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "10.5.1+c5fe779")]
[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
public static string GetMetaTitel(ISeoComposition that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "metaTitel");
```

Something happens when `that.Value<string>(publishedValueFallback, "metaTitel")` is called with the `publishedValueFallback`.

**Comment by Zeegaan** [comment]
@zharonar While I see your issue I'm having a little trouble on how to approach reproducing this 🤔 
would you mind coming up with a minimized example with steps I can follow? 🙏

**Comment by zharonar** [comment]
> @zharonar While I see your issue I'm having a little trouble on how to approach reproducing this 🤔 would you mind coming up with a minimized example with steps I can follow? 🙏 (with code snippets if they are needed)

Here are exact steps you need to follow to get this working:

1. Create Homepage doctype
2. Create Seo composition with one property named Title as string and use it on Homepage doctype
3. Generate models with modelBuilder
4. Create class "SEO" and inherit generated Composition

I.e. how it should look:

```
public class SEO : SeoComposition
{
    private readonly IPublishedContent _publishedContent;

    private string? _pageTitle;
    public override string PageTitle => _pageTitle ??= string.IsNullOrEmpty(base.PageTitle) 
        ? _publishedContent.Name!
        : base.PageTitle;
        
    private string? _metaTitle;
    public override string MetaTitel => _metaTitle ??= string.IsNullOrEmpty(base.MetaTitel)
        ? _publishedContent.Name!
        : base.MetaTitel;

    public new string? ShareBild => base.ShareBild!=null 
        ? base.ShareBild.Url(mode:UrlMode.Absolute) //take share image if exists
        : _publishedContent.HasProperty("heroImage") && _publishedContent.Value<MediaWithCrops>("heroImage")?.Content!=null 
            ? _publishedContent.Value<MediaWithCrops>("heroImage")!.Url(mode:UrlMode.Absolute) //take hero image
            : _publishedContent.Value<MediaWithCrops>("shareBild", fallback: Fallback.ToAncestors)?.Url(mode:UrlMode.Absolute);//at last take parent shareImages
        
    public SEO(IPublishedElement content, IPublishedValueFallback publishedValueFallback) : base(content, publishedValueFallback)
    {
        _publishedContent = content as IPublishedContent ?? throw new ArgumentOutOfRangeException(nameof(content), "must implement IPublished Content also");
    }
}
```

Create BaseView that inherits UmbracoViewPage<IPublishedContent>

Create property 

```
private SEO? _seo;
public SEO SEO => _seo ??= Model is IPublishedContent content ? new SEO(content, new NoopPublishedValueFallback()) : throw new InvalidOperationException($"{nameof(T)} must implement IPublishedContent");
```

In the Homepage.cshtml use `@inherits BaseView<Homepage>`

Call SEO.Title and there lies the problem.


I hope this helps :)

**Comment by andr317c** [comment]
Hey,

I tried reproducing it and I got the same error. The reason for the error occurring is that you are using the NoopPublishedValueFallback, which doesn't implement the new members added in https://github.com/umbraco/Umbraco-CMS/commit/451d1cec6ab9ea3f1ea269fff3c4e95debfae5e7. However, NoopPublishedValueFallback is only intended for testing purposes.

A solution could be changing your BaseView to something like this:
```
public class BaseView<T> : UmbracoViewPage<IPublishedContent>
{
    private SEO? _seo;
    public SEO SEO => _seo ??= Model is IPublishedContent content ? new SEO(content, Context.RequestServices.GetRequiredService<IPublishedValueFallback>()) : throw new InvalidOperationException($"{nameof(T)} must implement IPublishedContent");
    
    public override Task ExecuteAsync()
    {
        return Task.CompletedTask;
    }
}
```

Note that this gets an actual PublidhedValueFallback instead of the NoopPublishedValueFallback.

I will create a PR that makes the NoopPublishedValueFallback implement the new interface member.

**Comment by nikolajlauridsen** [comment]
Fixed in #14227

**Comment by croban** [comment]
same bug still in 11.04.
There is a fix inside v11/dev branch obviously not deployed yet or?

**Comment by Zeegaan** [comment]
Yep its in the v11 branch, so will be a part of the next v11 release, and v12 👍
