### ISSUE TITLE
Backoffice slows down getting content with a lot of variants

### ISSUE THREAD

**Issue by dawoe** [umbraco/Umbraco-CMS#14936]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1 to 12.x

### Bug summary

We have a site with 6 languages. We also have uMarketing suite installed. For some pages multiple segment variants are created with uMarketing suite.

We noticed while adding more languages, and the customer creating personalized content with uMarketingSuite this slows down loading of content in the backoffice. The frontend runs just fine.

We noticed that getting a response from this API method is slow : https://github.com/umbraco/Umbraco-CMS/blob/cd2855634eb4528d003ec7080e3c8aa0002bc5e2/src/Umbraco.Web.BackOffice/Controllers/ContentController.cs#L460

On our live environment this takes up between 8 to 10 seconds to return a result. With the copy of the database of the live environment on our local machine this takes between 5 and 7 seconds.

Adding more variants (culture or segment) increases the response time. Removing variants decreases the response time.

We see the same behavior when use this database on a clean Umbraco install. So we can rule out uMarketing suite.

### Specifics

I did a debugging session against the Umbraco source code and found where the majority of time is spent. 

It happens in this method :
https://github.com/umbraco/Umbraco-CMS/blob/cd2855634eb4528d003ec7080e3c8aa0002bc5e2/src/Umbraco.Core/Models/Mapping/ContentPropertyDisplayMapper.cs#L35

This mapping function is called for each property in each variant. Because this happens in a loop we are executing code that is the same for all properties in all variants.
For example getting the datatype configuration.  But this is the same for all variants, so there is no need to get it over and over again.

This can be probably be improved by getting all this information earlier in the mapping process and pass it on using the MappingContext.

### Steps to reproduce

Create a site with a lot of culture variants. If needed install uMarketingSuite and some personalized content as well.

See the performance of the GetById degrading with each variant added.

### Expected result / actual result

Adding more variants should not slow down the retrieval of content significantly.

**Comment by Migaroez** [comment]
Hey @dawoe, Thx for the clear and complete bug description and investigating the possible culprit, going to have a look at this and will get back to you asap.

**Comment by ronaldbarendse** [comment]
We've implemented performance improvements in mapping code for a similar issue in PR https://github.com/umbraco/Umbraco-CMS/pull/10521 by storing/caching data in the `MapperContext`, exactly like you already mentioned. Calling `DataTypeService.GetDataType()` for every property (even if some use the same data type), multiplied by every culture and again multiplied by every segment does indeed cause _a lot_ of unnecessary overhead...

**Comment by Migaroez** [comment]
Intermediate findings:
Tested on v10/dev(132935c)
Used the following code https://gist.githubusercontent.com/Migaroez/162faab59d4d04515d665e27f50e2735/raw/e25436167c3882118699760c0760912bf244ff78/ContentGenerateController
And payload
```
{
    "amount":3,
    "doctypeAliases":["fifteenCultureDocType"],
    "containingDoctypeAlias":"container",
    "containtingDoctypeUsesListview" : "false",
    "newDocTypePropertyMinAmount":30,
    "newDocTypePropertyMaxAmount":30,
    "languageIsoCodes":["en-us","nl-nl","nl-be","fr-fr","dk-dk","fr-be","fr-en","aa","aa-DJ","aa-ER","aa-ET","af","af-NA","af-ZA","agq"],
    "segments" :["segmentOne","segmentTwo","segmentThree","segmentFour","segmentFive"]
}
```
Takes around 426ms to get one of these nodes trough the Backoffice on SQL Server Dev 16
and 289ms on sqllite
Without cultures, it takes around 57ms on sqllite.

So there definitely is an impact related to enabling and using segments but not anything dramatic as Dave is seeing. Granted, this is on a limited data set with only textbox properties.

Will continue the investigation

**Comment by Migaroez** [comment]
Increasing the nodes to 1000+ does not seem to mess with the median response time, but there are some random spikes, this might indicate some caching issues.
![image](https://github.com/umbraco/Umbraco-CMS/assets/6025797/adef23f5-210e-45b0-a1a5-e754920ab88a)

Since reproducing this on a blank installation seems to be not straight forward, I am going to request some dedicated time to investigate this in a future sprint.

**Comment by dawoe** [comment]
Hi @Migaroez and @ronaldbarendse 

Did some further digging myself. It's the mapping of BlockList properties that is taking up all the time on my end.

If I prevent the following lines being executed for the block list editor my page loads in about 500ms.

https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Models/Mapping/ContentPropertyBasicMapper.cs#L94

https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Models/Mapping/ContentPropertyDisplayMapper.cs#L50

https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Models/Mapping/ContentPropertyDisplayMapper.cs#L78

So there is something fishy going on when getting the data for the block list editor.

**Comment by cornehoskam** [comment]
After trying out the possible pullrequest by @dawoe, the performance seems to be improved for all intents and purposes that use the ContentService to fetch content from a uMarketingSuite perspective, especially when fetching content items in bulk.

**Comment by dawoe** [comment]
I just did some digging. Our customer started reporting a slow backoffice after we upgraded from 10.2.x to 10.4.x

**Comment by techcolin** [comment]
I'd like to chime in on this issue but from a different perspective.   Apologies as I don't want to cause confusion, but need to see if there's a relationship here.

Our client is on v8.18.7 and has an instance with 17 language variants.  There are serious issues with backoffice performance we've not reported as we've been due to upgrade since Feb last year.  With delays we're now confirmed to be upgrading to v13 shortly.  I'm concerned the issue we're seeing will still exist, as this ticket seems to correspond to what we're seeing.

To summarise, when we load a page in the BO GetById can take generally 10 to 17 seconds to return.  The speed depends on the number of blocks, but at best we're seing 7-8 seconds load time for any page.

It seems like Umbraco is loading ALL content for ALL variants despite the BO admin being in a single culture context for the editor. 

Can anyone confirm if the upgrade is likely to solve anything here before we go too far?  If we can assist with additional info please let me know as I appreciate this is quite an unusual site that makes heavier use of variants than most.

**Comment by bielu** [comment]
@dawoe I spend time playing around with backoffice and this happens not only when you have a lot variants(I have just one variant), but also when you have a lot nested blocks in grid block list editor... my times just by introducing simple decorator such as:
```
public class DataTypeServiceCacheDecorator : IDataTypeService
{
    private readonly IDataTypeService _dataTypeService;
    private readonly IAppPolicyCache _runtimeCache;

    public DataTypeServiceCacheDecorator(IDataTypeService dataTypeService, AppCaches caches)
    {
        _dataTypeService = dataTypeService;
        _runtimeCache = caches.RuntimeCache;
    }

    private string GetCacheKey(string operationName, params object[] args) =>
        $"DataTypeServiceCacheDecorator_{operationName}_{string.Join("_", args)}";
    private T GetCachedResult<T>(string cacheKey, Func<T> operation) =>
        _runtimeCache.GetCacheItem(cacheKey, operation, TimeSpan.FromMilliseconds(20));
    public IReadOnlyDictionary<Udi, IEnumerable<string>> GetReferences(int id) => GetCachedResult(GetCacheKey(nameof(this.GetReferences),id), ()=>_dataTypeService.GetReferences(id));

    public Attempt<OperationResult<OperationResultType, EntityContainer>?> CreateContainer(int parentId, Guid key, string name, int userId = -1) =>this._dataTypeService.CreateContainer(parentId, key, name, userId);

    public Attempt<OperationResult?> SaveContainer(EntityContainer container, int userId = -1) =>
        this._dataTypeService.SaveContainer(container, userId);

    public EntityContainer? GetContainer(int containerId) => GetCachedResult(GetCacheKey(nameof(this.GetContainer),containerId), ()=>_dataTypeService.GetContainer(containerId));

    public EntityContainer? GetContainer(Guid containerId) => GetCachedResult(GetCacheKey(nameof(this.GetContainer),containerId), ()=>_dataTypeService.GetContainer(containerId));

    public IEnumerable<EntityContainer> GetContainers(string folderName, int level) => GetCachedResult(GetCacheKey(nameof(this.GetContainers),folderName,level), ()=>_dataTypeService.GetContainers(folderName,level));

    public IEnumerable<EntityContainer> GetContainers(IDataType dataType) => GetCachedResult(GetCacheKey(nameof(this.GetContainers),dataType.Id,dataType.ParentId), ()=>_dataTypeService.GetContainers(dataType));

    public IEnumerable<EntityContainer> GetContainers(int[] containerIds) => GetCachedResult(GetCacheKey(nameof(this.GetContainers),containerIds), ()=>_dataTypeService.GetContainers(containerIds));

    public Attempt<OperationResult?> DeleteContainer(int containerId, int userId = -1) => this._dataTypeService.DeleteContainer(containerId, userId);

    public Attempt<OperationResult<OperationResultType, EntityContainer>?> RenameContainer(int id, string name, int userId = -1) => this._dataTypeService.RenameContainer(id, name, userId);

    public IDataType? GetDataType(string name) =>GetCachedResult(GetCacheKey(nameof(this.GetDataType),name), ()=>_dataTypeService.GetDataType(name));

    public IDataType? GetDataType(int id) =>GetCachedResult(GetCacheKey(nameof(this.GetDataType),id), ()=>_dataTypeService.GetDataType(id));

    public IDataType? GetDataType(Guid id) =>GetCachedResult(GetCacheKey(nameof(this.GetDataType),id), ()=>_dataTypeService.GetDataType(id));

    public IEnumerable<IDataType> GetAll(params int[] ids) =>GetCachedResult(GetCacheKey(nameof(this.GetAll),ids), ()=>_dataTypeService.GetAll(ids));

    public void Save(IDataType dataType, int userId = -1) => this._dataTypeService.Save(dataType, userId);

    public void Save(IEnumerable<IDataType> dataTypeDefinitions, int userId = -1) => this._dataTypeService.Save(dataTypeDefinitions, userId);

    public void Delete(IDataType dataType, int userId = -1) => this._dataTypeService.Delete(dataType, userId);

    public IEnumerable<IDataType> GetByEditorAlias(string propertyEditorAlias) =>GetCachedResult(GetCacheKey(nameof(this.GetByEditorAlias),propertyEditorAlias), ()=>_dataTypeService.GetByEditorAlias(propertyEditorAlias));

    public Attempt<OperationResult<MoveOperationStatusType>?> Move(IDataType toMove, int parentId) => this._dataTypeService.Move(toMove, parentId);
}
```
went down from from 30s to just 8...  so yeah something fishy is going on with block editor

**Comment by techcolin** [comment]
@bielu which version is this on?

**Comment by bielu** [comment]
@techcolin I am on v13.0.3

**Comment by techcolin** [comment]
Thanks @bielu for confirming.  This is bad news that I'll need to break to our client, and I suspect not an easy thing to re-architect from @UmbracoHQ's point of view.

It would be good to get Umbraco's feedback on this one.  Given that we're on v8, and yet there seems to be further slowdown within v10 as reported above, and ongoing performance issues on v13 I think we're in trouble.

For what it's worth, this time last year we increased our VM to 4-core 16GB ram to try and improve things, and even went on to a Premium Azure SQL tier (very expensive) to see how much it helped.  Things improved, but not to the degree we hoped.  Without running any specific programatic tests I came to the conclusion that it is the sheer number of queries Umbraco BO is running to load the content, each with its own latency, that was causing the slowness rather than large expensive queries.

**Comment by bielu** [comment]
I spend some time debuging umbraco source code and this doesnt make sense for me. We are using IDataTypeService, which later speaks with DataTypeRepository which caches everything for 5 minutes. which means we should not see much delay because of speaking to IDataTypeService...  So I noticed the cache works in some context and some not, I couldn't see any logic which would determine why it is not always cached when speaking with IDataTypeService.

**Comment by bielu** [comment]
So I had play around with umbraco source code and added mapperContext to method ToEditor. and there is comparison:
<img width="837" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/2244074/c37e5139-45fc-4b87-9909-3f30a6c1f554">

this is current results:
<img width="914" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/2244074/7cc270c9-c59b-41fa-b217-51a389d273b4">
I removed almost 250 usages of datatype service, which removed over 2/3 of time. So when added custom profiling with decorator I finally started understanding what is happening, the Runtime cache is takes around 0.75ms to respond to query, a nd just because of volume we would add 150ms just to read from it, on top of it there are operation on each of datatypes which takes between 0.5 up to 2.5 ms per datatype so there is coming another 240ms! so it is just volume of request to runtime cache and on top overoperations which takes majority of processing time.

**Comment by miguelcrpinto** [comment]
@bielu do you know if V8 was also affected by this?

We have a V8.18.12 instance with way more nodes (I'd say more than 15k) and that often takes minutes to publish pages with lots of blocks in a block list property. In our case, even though we have quite a few languages enabled in the CMS, we are not using the language variants.

Loading such nodes in the backoffice also takes a while (nearly 1 minute just the GetById API call)

**Comment by bielu** [comment]
@miguelcrpinto yes v8 would be affect by this. My pr addresses this, but afaik if this PR will be merged I dont think so it will be backport to v8, especially as this pr is pretty intrusive to and use default interface implementations, which wouldn't work in v8 (but I might be wrong)

**Comment by Migaroez** [comment]
Hey @dawoe, have you had the chance to test your setup on 13.2.0-RC?

**Comment by dawoe** [comment]
@Migaroez  I just tested it.

Our page with the most variants now loads in under 500ms.

**Comment by erwindamsma** [comment]
Will this solution also be released for v10?

**Comment by Migaroez** [comment]
@dawoe That is amazing news 🚀 

@erwindamsma we are looking into it, we want to and it should be possible, there are just a few time constraints right now.

Might have an ETA next monday.

**Comment by erwindamsma** [comment]
Any update on the ETA?

**Comment by erwindamsma** [comment]
Hey @Migaroez,

Any idea if (and when) the fix will be available for Umbraco 10?

**Comment by Migaroez** [comment]
Hey @erwindamsma, sorry for the late reply, been busy and sick for a while. Still trying to catch up.

Our current stance is that we will not invest the time to backport this to v10/12 at the moment due to everyone being hands on with v14 and the upgrade path from v10 to v13 should be very straight forward.

**Comment by gurumurthyjv** [comment]
Hello All,

Does the back office slowness with multiple variants enabled node is fixed in v13 ?  or is it planned for any features releases.

We are facing issue while saving & publishing, content with 24 variants in Umbraco **v12.3.6**, it almost takes 5min per save or publish, even it will be more in some cases.

Regards,
Gurumurthy JV

**Comment by dawoe** [comment]
Hi @gurumurthyjv 

This has been fixed in 13.2.0

**Comment by bielu** [comment]
@dawoe it is not fixed, it is mitigate :), it still slowing down but now it is less direct hit :)

**Comment by gurumurthyjv** [comment]
@dawoe ,

Do we have any timelines like when this will be fixed in v13 ?

Thanks @bielu , for responding  👍 

Thanks,
Gurumurthy JV

**Comment by bielu** [comment]
@gurumurthyjv there is no time line for this afaik, 
also just upgrading to 13.2 will resolve your issue, unless we speak about thousands of variants, where is issue still persist :)

**Comment by gurumurthyjv** [comment]
Hi @bielu and @dawoe ,

I have upgraded from v12 to v13.3, but still the save & publishing is taking more then 1min, which was not the case in v8 (less then 15sec).
we have around 24 variants for each node.

Does this 1min for each save is desirable ?

Regards,
Gurumurthy JV

**Comment by bielu** [comment]
Hey @gurumurthyjv, that sounds weird are you using any publish/save notifications? If so are you using data type service?

**Comment by gurumurthyjv** [comment]
Hi @bielu ,

Yes, we do have these notifications ContentPublishedNotification,SendingContentNotification and ContentSavedNotification for our custom requirement's.

**Comment by bielu** [comment]
@gurumurthyjv can you disable them and check if performance is better without? As than we know where to look 😉

**Comment by gurumurthyjv** [comment]
Hi @bielu ,

Thanks for your response, after disabling the content notifications, I don't see any differences. its the same.

**Comment by bielu** [comment]
@gurumurthyjv if you can create example project which will reproduce issue as you have than I can profile it and propose additional adjustments to speed up things :)

**Comment by techcolin** [comment]
We have just upgraded our v8 instance to v13.3 so we have some timings to share.

The worst page we have has 13 variants, and 65 blocks including nested components.  Some of these have settings on them to control background colours and alignment etc.  Appreciate this is an unusually large page, but it's something that was developed to client requirements at the time and not expected to suffer any issues.

We see some improvement, but not enough really, particularly around publishing.

Back-Office Page Load: 
U8 = 18.54 seconds
U13 = 13.5
Improvement: 28%
 
Save single language:
U8 = 80 seconds
U13 = 43.5 seconds
Improvement: 45%
 
Publish UK variant:
U8 = 88 seconds
U13 = 80 seconds
Improvement: 10%

**Comment by bielu** [comment]
@techcolin as mentioned earlier I can spend time profiling things and make additional suggestions to HQ to improve things, but I need example solution which suffers biggers issue than mine as I managed to be only at 5s top post fix.

Also can you maybe share what infrastructure you have as that would help also determine what bottle neck you have.

**Comment by techcolin** [comment]
Both the v8 and v13 environments are running on Azure VMs - both D4as 4-core 16GB RAM with SSDs.
SQL Azure elastic pool for the databases on 200 eDTUs, but under no load whatsoever.

Creating a test instance might be tricky as we're very busy at the moment.  We could definitely supply uSync files if that helps at all?

**Comment by bielu** [comment]
Depends on what you mean by usync files, if you can include content in then they will deffo help, if just document types that they will help but much less

**Comment by erwindamsma** [comment]
> Hey @erwindamsma, sorry for the late reply, been busy and sick for a while. Still trying to catch up.
> 
> Our current stance is that we will not invest the time to backport this to v10/12 at the moment due to everyone being hands on with v14 and the upgrade path from v10 to v13 should be very straight forward.

We migrated the Umbraco 10 site to the latest v13, but just like @techcolin, not all has been resolved. We went from save times of approximately 60 seconds to around 34 to 38 seconds.

The same client also has some legacy sites (in the same Umbraco) using nested content instead of the blocklist editor. Those save within 1 tot 2 seconds, and sometimes even in less than a second.

**Comment by techcolin** [comment]
All.

We noted the release of 13.4 last week and have just upgraded our problem site to test on a staging server.
https://our.umbraco.com/download/releases/1340

Happily, we can report on initial findings that our block-heavy page has improved from 26.8s load time for the main for GetById call, down to 3.98s

<img width="889" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/40235909/60c1ac0a-705c-453d-af19-0716aec4b4ca">

<img width="880" alt="image" src="https://github.com/umbraco/Umbraco-CMS/assets/40235909/6e71d11b-3e5e-4b1a-9b44-0f44d0558686">


This looks like the fix we were looking for.  Obviously do your own testing, and note we haven't tested the upgraded version end-to-end, just had a look from this performance point of view.

**Comment by nielslyngsoe** [comment]
As @dawoe (the issue reporter) and now @techcolin have reported great improvements, I will consider this specific issue as completed. (As well, there hasn't been any activity on this issue for over half a year.)

That does not mean that it is perfect, but please initiate a new Issue with further specific details and reproduction steps. In this way, we can get a focused issue on the specific matters.

Thanks for all the effort. I'm delighted that this specific matter has been improved, and please keep it coming when other measurable situations occur.
