### ISSUE TITLE
IPublishedContent.HasValue() throws exception if segment is null

### ISSUE THREAD

**Issue by benmurphycb** [umbraco/Umbraco-CMS#14954]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.2

### Bug summary

We are using uMarketingSuite.

Our solution has a sitemap generator, where we loop through valid nodes and try to check if the IPublishedContent has a value:
```
var hideFromSitemap = content.HasValue("hideFromSitemap") 
    ? content.Value<bool>("hideFromSitemap")
    : false;
```

This throws an exception: `Value cannot be null. (Parameter 'key1')`
Unless we specify the segment as an empty string when trying to use .HasValue / .Value

### Specifics

I have managed to track this back in the Umbraco code: 
The issue is with the `Umbraco.Cms.Infrastructure.PublishedCache.GetSourceValue(string? culture = null, string? segment = null)` method - the return statement is:

```
return _sourceValues.TryGetValue(
    new CompositeStringStringKey(culture, segment),
    out SourceInterValue? sourceValue)
    ? sourceValue.SourceValue
    : null;
```

The issue is that when newing up the `CompositeStringStringKey`, the segment is still null and not an empty string. 
The `CompositeStringStringKey` is expecting a string, not a nullable string. 

From what I can see - the segment should be set by this line: 
`_content.VariationContextAccessor.ContextualizeVariation(_variations, _content.Id, ref culture, ref segment);`

But this method (`Umbraco.Extensions.VariationContextAccessorExtensions.ContextualizeVariation()`) will not always assign this to an empty string if it cannot get the segment.

The null coalescing operator in this code:

```
segment = contentId == null
    ? publishedVariationContext?.Segment
    : publishedVariationContext?.GetSegment(contentId.Value);
```

means that it can still end up being null, which then causes the exception to be thrown with the `CompositeStringStringKey` initialization mentioned above.

Is this an issue with how the site is set up, or should the code be:

```
segment = contentId == null
    ? publishedVariationContext?.Segment ?? ""
    : publishedVariationContext?.GetSegment(contentId.Value) ?? "";
```

?

![image](https://github.com/umbraco/Umbraco-CMS/assets/54355060/1026fdcc-1313-44d0-82c9-192370180a58)

![image](https://github.com/umbraco/Umbraco-CMS/assets/54355060/d55958ff-caa8-491b-8ecf-c9a69026f97b)

### Steps to reproduce

Using Umbraco 10.4.2

1. Create a site that has document types that vary by culture and segment.
2. Create a sitemap generator that works as middleware that runs when the following route is hit "/sitemap.xml" 
3. This sitemap generator takes a start node and culture, then uses `_umbracoContextFactory.EnsureUmbracoContext()` to get the context, before recursively getting the relevant nodes and child nodes and adding these to a list. 
4. Iterate through this list, and try check if each node has the hideFromSitemap property: `IPublishedContent.HasValue("hideFromSitemap")`
5. If it does, get this value as a bool
6. If not, default to false

When using the .HasValue / .Value methods the exception should be thrown. 

### Expected result / actual result

The segment falls back to an empty string if it cannot be found so that it can be used in a CompositeStringStringKey.

**Comment by kjac** [comment]
Hi @benmurphycb,

Thank you for reaching out and for your very detailed description and research 💪 

However, I can't quite reproduce the issue. 

First and foremost I haven't installed uMarketingSuite, just to make sure I'm only testing Umbraco.

Next, I have enabled segments in code and created a doctype with segments and various permutations of properties
- with culture variation
- with segment variation
- with culture _and_ segment variation
- with no variation whatsoever

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/be7dee7d-2d08-4d18-b63d-7ff8b1223453)

![image](https://github.com/umbraco/Umbraco-CMS/assets/7405322/bb54dbe3-04cf-4bc8-a6b7-d987a3b90b21)

Next I'm outputting the content using a template like this:

```cshtml
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage
@{
	Layout = null;
}
<html lang="en">
<head>
    <title>Issue 14954 test template</title>
</head>
<body>
<ul>
    @foreach (var property in Model.ContentType.PropertyTypes)
    {
        <li>Property <b>@property.Alias</b> has value: <b>@Model.HasValue(property.Alias)</b></li>
    }
</ul>
<ul>
    @foreach (var property in Model.Properties.Where(property => property.HasValue()))
    {
        <li>Property <b>@property.Alias</b> value is: <b>@Model.Value(property.Alias)</b></li>
    }
</ul>
</body>
</html>
```

...and a `RenderController` that applies segments from a `segment` query parameter. It all seems to work just fine:

[14954.webm](https://github.com/umbraco/Umbraco-CMS/assets/7405322/c93054c5-c37a-4730-bd16-fed71b4b1178)

It also works fine with content that is non-variant (outputs the same across all of the segments).

I'm testing on 10.7, but I doubt that things around segment handling has changed from 10.4. Question is... did I misunderstand your issue, or would the above approach yield the same error on your site?

**Comment by kasparboelkjeldsen** [comment]
We are seeing the same error on some properties on an Umbraco 8 upgraded to Umbraco 13. 

HasValue gets called with culture = "" and segment = null and fails out on ContextualizeVariation
If I set segment to "" while debugging we get through just fine and receive the expected null value.

**Comment by SATC-Ben** [comment]
We are also getting this issue in V13.0.3 when upgrading from 11 and after adding culture setting's to an existing site. It occurs when we run a custom indexing process and trying to access `.Value<>`
```
if(node.Value<bool>(_publishedValueFallback, "hideFromSearch"))
```
The error:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key1')
   at Umbraco.Cms.Core.Collections.CompositeStringStringKey..ctor(String key1, String key2)
   at Umbraco.Cms.Infrastructure.PublishedCache.Property.CacheValues.For(String culture, String segment)
   at Umbraco.Cms.Infrastructure.PublishedCache.Property.GetValue(String culture, String segment)
   at Umbraco.Extensions.PublishedPropertyExtension.Value[T](IPublishedProperty property, IPublishedValueFallback 
   ublishedValueFallback, String culture, String segment, Fallback fallback, T defaultValue)
   at Umbraco.Extensions.PublishedContentExtensions.Value[T](IPublishedContent content, IPublishedValueFallback 
   ublishedValueFallback, String alias, String culture, String segment, Fallback fallback, T defaultValue)
   at ...Models.Generated.BasePageComp.GetTags(IBasePageComp that, IPublishedValueFallback publishedValueFallback) in 
   ..\Models\Generated\BasePageComp.generated.cs:line 455
   at ...Models.Generated.Home.get_Tags() in ...\Models\Generated\Home.generated.cs:line 223
   at ...Components.Indexing.SearchContentIndexer.SetTagField(IndexingItemEventArgs e, IPublishedContent node) in 
   ..\Components\Indexing\SearchContentIndexer.cs:line 352
```
No extensions or UMarketingSuite either.

**Comment by SlawekSkiba** [comment]
Any news about this problem?

**Comment by kjac** [comment]
This should be solved along with #16753 by #17024 for V13.5 👍

**Comment by craigFactory73** [comment]
I'm still seeing this issue in umbraco 13.8.1. 

Within my : 
```
public void Handle(UmbracoApplicationStartingNotification notification)
{
indexProvider.TransformingIndexValues  += InsertCustomValuesIntoLuceneIndex
}
```

Whenever I try to get the Value of a field using the code below I see the error:
`System.ArgumentNullException: 'Value cannot be null. (Parameter 'key2')'`

```
private void InsertCustomValuesIntoLuceneIndex(object sender, IndexingItemEventArgs e)
{
  using (var umbracoContext = _umbracoContextFactory.EnsureUmbracoContext())
  {
  	var cache = umbracoContext.UmbracoContext.Content;
  	page = cache.GetById(PageId);
  
          **BlockListModel blocklist = page.Value<BlockListModel>("blocks");**
  }
}
```

if I change the last line to:
`BlockListModel blocklist = page.Value<BlockListModel>(sectionsFieldName, "", "");`

It works as expected. but the signature for the IPublishedContent.Value() method show the segment parameter having a default value of null [string? segment = null]
