### ISSUE TITLE
Login using external provider doesn't respect returnPath parameter of login screen

### ISSUE THREAD

**Issue by skttl** [umbraco/Umbraco-CMS#15686]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.1.0

### Bug summary

When loggin in using an external provider the returnPath parameter of the login screen is not respected, and the user is returned to the backoffice, instead of where the returnPath parameter describes.

This is problematic eg. when enabling basic authentication for the frontend, where the user expects to be sent to the frontend upon signing in, but instead ends up in the backoffice.

v12 is also affected, so it's not something that was added with the new login screen.

### Specifics

When going to a site that has basic authentication enabled, the user gets redirected to `/umbraco/login/?status=false&returnPath=%2F`, notice the returnPath sitting at `/` for the homepage of the website.

If you log in using a regular Umbraco user from the db using a username and a password, you get redirected correctly to `/`.

But if you add an external login provider, eg. using the AzureSSO package, or Umbraco ID, you get redirected to the backoffice.

### Steps to reproduce

Enable Basic Authentication by adding the following to your app settings

```
      "BasicAuth": {
        "Enabled": true,
        "RedirectToLoginPage": true,
        "SharedSecret": {
          "Value": "something"
        }
      },
```

Install and configure some kind of external login provider - Umbraco ID, AzureSSO or similar.

Go to your website (make sure you are not logged in to the backoffice already).

Notice you are redirected to `/umbraco/login/?status=false&returnPath=%2F` with the returnPath provider pointing to the url you tried to get.

Log in using the external provider

### Expected result / actual result

Expected to be redirected back to the originally requested page (eg. `/`). Actually got redirected to the backoffice.

**Comment by Zeegaan** [comment]
Hmm I know we've seen this in v12 with this: https://github.com/umbraco/Umbraco-CMS/issues/15259
But seems like that should be fixed, so seems like there's something else breaking this again 🙈

**Comment by skttl** [comment]
Sorry, I wrote v12 is also affected - it actually isn't, I mixed things up on that. But v13 definitely is :)

**Comment by Zeegaan** [comment]
Ah okay that makes sense, might be related to the new login screen, I'll have a look to reproduce 😁

**Comment by Zeegaan** [comment]
This also happens on 10, so it seems like its not related to the new login screen at least 😁
But I can reproduce this 👍 
I've put it up for grabs for now, as we'd love some help with this 😁

**Comment by skttl** [comment]
If you can give some pointers, I can take a stab at it. Just don't know where to start :)

**Comment by Zeegaan** [comment]
I am honestly not sure myself either 🙈 Think best bet would be to see where the request ends up after authenticating via Basic auth, and then go from there 👍 I am betting it hits the backoffice controller `Login` action, so I think setting a breakpoint there and then stepping through would be a good starting point 😁

**Comment by jrunestone** [comment]
I've been at this issue a number of times before (#13011, #13026, #14423, #14198) and it's resurfaced again :roll_eyes: (in v13)

It's become a priority for us so I'm dedicating a bit of time for it...

**Comment by shearer3000** [comment]
hi - any update on this?

**Comment by jrunestone** [comment]
Hi, we've merged [this PR](https://github.com/umbraco/Umbraco-CMS/pull/16049) that fixes one part of the problem (honoring the `returnUrl` query param if it's in the url) - the problem now is that the `returnUrl` query parameter isn't sent along at all.. I suspect it's some JS code somewhere that loses it but I haven't found it yet.

It's vacation time here for a couple more weeks so no work done here on my side.

**Comment by Neirijnck** [comment]
Hi,
Any update on this?
Still experiencing the issue where returnpath is not working after login in version 13.7.2
Thanks!

**Comment by iOvergaard** [comment]
Hi all

According to this comment https://github.com/umbraco/Umbraco-CMS/issues/16772#issuecomment-3575289255, this issue was resolved by upgrading to version 13.12.0 (and beyond). It may very well have been fixed as part of this PR #19984.

I would suggest trying that out, and if it does not work, then please come back and reopen this issue.
