### ISSUE TITLE
Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 

### ISSUE THREAD

**Issue by konius** [umbraco/Umbraco-CMS#16163]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

Examine index gets corrupt and can't view or manage the Examine dashboard and any content trying to read index for display purpose becomes empty.

Happens on version 11.3.2, but also on 13.1.1 with the only solution to complete delete Examine folder and restart the application.

Issue is already discussed on [Our](https://our.umbraco.com/forum/using-umbraco-and-getting-started/109829-saving-requires-multiple-save-attempts-error-invalid-deletion-count-2-vs-doccount-1).

```
Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 (resource: BufferedChecksumIndexInput(SimpleFSIndexInput(path="C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\MembersIndex\segments_vd")))
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Umbraco.Cms.Infrastructure.Examine.ConfigurationEnabledDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Examine.Lucene.Providers.LuceneIndex.PerformIndexItemsInternal(IEnumerable`1 valueSets, CancellationToken cancellationToken)
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass49_0.<PerformIndexItems>b__0()
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass73_0.<QueueTask>b__0(Task x)
```

![image](https://github.com/umbraco/Umbraco-CMS/assets/3933562/3d097800-b618-40b3-ae48-be6a1cb8b791)

### Specifics

For an unknown reason the index gets corrupt and bricks the back office dashboard.

Application is hosted on Azure and config is applied as per this guide: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/fundamentals/setup/server-setup/azure-web-apps

### Steps to reproduce

N/A

### Expected result / actual result

Expected to be able to at least view the dashboard and rebuild indexes if they get corrupt.

**Comment by shallett-ghd** [comment]
We've been dealing this issue with Umbraco 10.6.1. It has been impossible to replicate in development environments but does present itself in large traffic client sites with a lot of content.

**Comment by Migaroez** [comment]
Might be related to 
https://github.com/umbraco/Umbraco-CMS/issues/15783

**Comment by sytexa-julia** [comment]
Just started seeing this after we rolled out our upgrade to 13.x. Strangely it's been working fine in App Service for over a year.

**Comment by marius-ruhrmann-syzygy** [comment]
Same problem here.
- Hosted on Azure in windows environment
- Member index is corrupted
- Quick fix from @TQ-Benji works, but it would be cool to have a fix very soon!

**Comment by kows** [comment]
still happens on 13.3.0, single instance app service.

**Comment by readingdancer** [comment]
We have the same issue on a client site running on 10.8.5

**Comment by sniffdk** [comment]
We are running into this problem as well on a 13.1.0 installation running on a single Azure App Service.
The error seems to start at random, a deletion of the examine folder and a site restart fixes it, but not for long.

We can't even use the api to rebuild the index, as that will throw the same "invalid deletion count" error.

This should definitely have a higher priority in getting fixed 🙏

**Comment by benbarnett02** [comment]
Just adding my 2 cents - Same issue continuing on 13.3.2.

Running on Azure App Service (free plan), Azure SQL, Azure storage account for media & imagesharp stuff.

**Comment by Marcin-Niznik** [comment]
same problem Umbraco v12.3.10 on Umbraco Cloud, ContentDeliveryAPI Index gets corrupted.

**Comment by sputnik-liam** [comment]
Experiencing this constantly running Umbraco 13.3.2 deployed to Azure using recommended config.
`Lucene.Net.Index.CorruptIndexException: invalid deletion count: 171 vs docCount=1`

It's especially troublesome as we don't have direct access to every customers infrastructure.

**Comment by seanrockster** [comment]
We're having this issue as well, it seems to be random. Had it a few weeks ago however removing the index files and restarting the webapp seemed to resolve it. However we're having the same issue. We've release some features and updates (same umbraco version 12.3.7) and we're suffering again. Removing the index files and restarting has had no affect.

Unfortunately our client relies on the member search because we have a custom index and searcher with member properties they need to search on - the standard searcher doesn't search on custom properties btw.

We're seeing different errors.

1. we're seeing the issue mentioned in this ticket
2. we're seeing log errors where examine is actually looking for filenames that do not exist, e.g.  its looking for _1k.si and the membersindex folder doesn't have that file name, its _1q.si

`System.IO.FileNotFoundException: Could not find file 'C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\MembersIndex\_1k.si'.
File name: 'C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\MembersIndex\_1k.si'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Lucene.Net.Store.MMapDirectory.OpenInput(String name, IOContext context)
   at Lucene.Net.Store.Directory.OpenChecksumInput(String name, IOContext context)
   at Lucene.Net.Codecs.Lucene46.Lucene46SegmentInfoReader.Read(Directory dir, String segment, IOContext context)
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFileAnonymousClass.DoBody(String segmentFileName)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
--- End of stack trace from previous location ---
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run(IndexCommit commit)
   at Lucene.Net.Index.SegmentInfos.FindSegmentsFile.Run()
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Umbraco.Cms.Infrastructure.Examine.ConfigurationEnabledDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Examine.Lucene.Providers.LuceneIndex.GetLuceneDirectory()
   at Examine.Lucene.Providers.LuceneIndex.IndexReady()
   at Examine.Lucene.Providers.LuceneIndex.PerformIndexItemsInternal(IEnumerable`1 valueSets, CancellationToken cancellationToken)
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass49_0.<PerformIndexItems>b__0()
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass73_0.<QueueTask>b__0(Task x)`

**Comment by seanrockster** [comment]
Deleting all of the examine indexes and restarting the webapp restored the indexes correct.

**Comment by sniffdk** [comment]
@seanrockster good to hear

But this seem to be a very common problem, would love to get some kind of HQ feedback here 😅

**Comment by sputnik-liam** [comment]
@seanrockster this is a known quick fix, but doesn't solve the underlying problem that has been a documented issue for a long time and theres been little to no formal communication from Umbraco on this.

**Comment by sniffdk** [comment]
Tagging @nul800sebastiaan 🙈

**Comment by authoritymikael** [comment]
Deleting the examine indexes did it. But waiting for a permanent fix.

**Comment by AdamKronquistToxic** [comment]
We have experienced this on 8.18.14, 10.8.6 and 13.3.2.

**Comment by kevinstampe** [comment]
Also happening on 13.3.1, hosted in azure app service with azure sql db

**Comment by Migaroez** [comment]
Hey y'all, we are aware that these issues exist, but we have strong suspicions these things are popping up due to misconfiguration of azure web apps/load balancing/slot swapping. To be able to determine whether these issues are related to misconfiguration/bugs in examine/bugs in Umbraco, we are trying to build a troubleshooting guide, this will take some time still. In the meantime I advice you to read up on the issue @kevinstampe linked over on the examine repo (https://github.com/Shazwazza/Examine/issues/382#issuecomment-2158962439)
and the docs concerning azure/examine
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps#lucene-examine-configuration
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps#what-are-azure-web-apps

You can check a few of these configurations with @warrenbuckley's RuntimeValidators
https://github.com/Gibe/Umbraco.Community.RuntimeValidators

Hope to get back to you soon.

**Comment by sniffdk** [comment]
@Migaroez As @paulsterling writes here: https://github.com/Shazwazza/Examine/issues/382#issuecomment-2189532338 this is also an issue on a default Umbraco Cloud v. 13.4.0 configuration.
From your statement, that would mean, that the build-in configuration in Umbraco Cloud is faulty as well?

**Comment by eqtr-ab** [comment]
+1 for another site hosted in Umbraco Cloud encountering this same problem.

**Comment by mbogunovic** [comment]
Okay everyone, as @Shazwazza mentioned on https://github.com/Shazwazza/Examine/issues/382. This could be due to:
1. Examine config being set to default here https://docs.umbraco.com/umbraco-cms/reference/configuration/examinesettings and we are all trying to use multi-instance load-balancer setup
2.  I will try to apply and if I never come back to this post, means it works... 👯       "Examine": {
        "LuceneDirectoryFactory": "TempFileSystemDirectoryFactory"
      }
3. IN THEORY: This should indicate the examine to to create different cache path taking into an account hosting environment name so indexing doesn't get mixed up between two environment causing errors and inconsistencies.

Cheers!

**Comment by seanrockster** [comment]
We've upgraded to 13.4 and we are still having this issue. This is impacting our business, not good. @UmbracoHQ

**Comment by seanrockster** [comment]
Its logging this error every second, and the members index refuses to rebuild.

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\MembersIndex\segments_3'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at Lucene.Net.Store.Directory.Copy(Directory to, String src, String dest, IOContext context)
--- End of stack trace from previous location ---
   at Lucene.Net.Store.Directory.Copy(Directory to, String src, String dest, IOContext context)
   at Lucene.Net.Replicator.IndexReplicationHandler.RevisionReady(String version, IDictionary`2 revisionFiles, IDictionary`2 copiedFiles, IDictionary`2 sourceDirectory)
   at Lucene.Net.Replicator.ReplicationClient.DoUpdate()
   at Lucene.Net.Replicator.ReplicationClient.ReplicationThread.Run()

**Comment by Shazwazza** [comment]
@seanrockster please see this for now and do use the different factory as a work around for now https://github.com/Shazwazza/Examine/issues/382#issuecomment-2163520075

There's been some work on this recently to try to address all of this, but will require a beta release and some testing (next week). In the meantime, you should use UmbracoTempEnvFileSystemDirectoryFactory

**Comment by seanrockster** [comment]
@Shazwazza Ok tried that, causes the app to restart and now I get HTTP Error 500.30 - ASP.NET Core app failed to start. OMG this is a high volume ecommerce site, it cannot be donw.

**Comment by seanrockster** [comment]
@Shazwazza that didn't work and brought the site down with some error - i'll check the log for the exact error but had to revert to TempFileSystemDirectoryFactory

**Comment by seanrockster** [comment]
Not sure why but i think the db was timing out and that was the cause of the 500, i'm getting a timeout when I run the app via kudu. However after 4-5 restarts the app starts again. That did not happen on v12 as we restarted if often to rebuild the member indexes. The azure db is S6 400dtu and it smashes it, maxes the DTUs while starting.

**Comment by Shazwazza** [comment]
@seanrockster Yes there is a reason why the DB will get smashed. I've spoken about this issue at length in a couple Code Garden presentations and is also why I created [ExamineX](https://examinex.online/) so that you can have your indexes persisted in a managed service instead of in local Lucene files, this avoids index rebuilds, issues with Lucene files in Azure, etc... 

To re-cap this https://github.com/umbraco/Umbraco-CMS/issues/15783#issuecomment-2079534384:

> The 'Synced' directory is there to avoid performance implications of rebuilding indexes on startup when a site is moved to another worker in Azure. That is the only reason it exists, and it can only be used on your Primary node. If you aren't load balancing and don't care about this performance hit, than change it to Temp (local only storage). If you think that there isn't any overhead, think about this: If you scale out to +5 nodes in a load balancing setup, that means that 5x nodes will be performing index rebuilds around the same time, this means that your DB is going to get pummeled by queries to build all of those new indexes. The performance hit isn't the index building - it is the DB queries and this can lead to DB locks and lead to the dreaded SQL Lock Timeout issue in the back office. Plus, if search is critical to your front-end, than for a while after your site has started up, there won't be any index which means there won't be any search until the background processing is done. Many of these reasons is why [ExamineX](https://examinex.online/) was created.

* UmbracoTempEnvFileSystemDirectoryFactory was introduced in Umbraco here https://github.com/umbraco/Umbraco-CMS/pull/15571 (not sure what version that is released in), else if you are on an older version than TempFileSystemDirectoryFactory can be used. This will result in indexes being rebuilt anytime your site is moved to another worker (see above)
* The SyncedFileSystemDirectoryFactory attempts to work around this challenge where indexes are just local files. It attempts to syncronize a copy of the indexes in temp storage to main file storage on azure so that when a site is moved to another worker, it can sync from main storage to local storage to work from in order to avoid the index rebuild. 

The problem with SyncedFileSystemDirectoryFactory is that this implementation doesn't take into account what happens if the index files in your main storage become corrupted which can happen for a number of reasons - misconfiguration, network latency, process termination, etc... I've been helping the Umbraco team with a fix for this and will publish an Examine release for that next week.

**Comment by sniffdk** [comment]
Ohh my, this is such a mess 😬 
I do look forward to a SomewhatFixedUmbracoSyncTempEnvFileSystemDirectoryFactory or whatever naming is gonna rival the best Microsoft can come up with 😄 

@Shazwazza thank you for taking the time to help out on this 🙏 
Even though this really is a responsibility of HQ, as I see it. They ship a product, that is clearly broken even when running on their own infrastructure.

Perhaps ExamineX should have a better bundling option on Cloud setups going forward 🤔

**Comment by paulsterling** [comment]
Yes...that's my vote > to offer Examine X as part of Umbraco Cloud! It does solve the fundamental issues with Lucene and Azure App Services. Whatever is done with current Examine will be a workaround at best.

**Comment by ProudSebastiaan** [comment]
@Shazwazza I see it hasn't been released yet, do you have an update as to when you expect to have this fix deployed? We have a customer that has cbeen having corrupt index errors for over a year now without us being able to fix the problem. Lots of headache. This would be a lifesaver for us.

**Comment by Shazwazza** [comment]
Examine 3.3.0 has been published, release notes are here https://github.com/Shazwazza/Examine/releases/tag/v3.3.0

**Comment by Mikkel-Veyhe-jepsen** [comment]
We're still experiencing this issue having just updated to U13.5.1, our understanding was that Examine 3.3.0 was part of Umbraco 13.5.
Site hostet in Azure, no load balancing, using the SyncedTempFileSystemDirectoryFactory. We had internal, external and a custom siteSearch index fail this morning.
Quickfix of deleting indexes and restarting still works to fix it temporarily.

**Comment by sniffdk** [comment]
Hi @AndyButland 
This issue is not resolved yet.
We are still experiencing this issue on Umbraco 13.4.1 and Examine 3.3.0 🤷 

This is the error we see in the log:
![image](https://github.com/user-attachments/assets/1fc1c5c8-932e-490b-a2dc-15fa1423522e)

Or is that because we use the SyncedTempFileSystemDirectoryFactory as opposed to the SyncedFileSystemDirectoryFactory mentioned in @Shazwazza 's post ?

**Comment by AndyButland** [comment]
I agree... sorry, it seems I inadvertently closed it when referencing this issue in an related PR from another project.

**Comment by InfiniteSpirals** [comment]
Not sure if this will help anyone, but on investigating our own instance of this issue, I stumbled across the fact that the Azure app service plan had been set up with Zone Redundancy, which requires a minimum of 3x instance count.  This wasn't made clear when provisioning the service -  so the production site was running on multiple instances without proper load balancing configuration. I'm sure this contributed in some way to all the indexing issues we were having. I wonder if others are running on multiple workers without knowing. Checking the umbracoServer table for active instances would show this if so.

**Comment by Shazwazza** [comment]
@sniffdk That is a different stack trace than any previous one. `invalid deletion count` is new to me. If you have a way to replicate this please send me the info. (i.e. a copy of your indexes)

**Comment by kows** [comment]
My trace after Azure machine move:
Starts with
"MembersIndex" index is corrupt, a new one will be created

`Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 (resource: BufferedChecksumIndexInput(MMapIndexInput(path="C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\MembersIndex\segments_eos")))
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)`
   
   Then
   An error occurred processing the index batch.
   `Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 (resource: BufferedChecksumIndexInput(MMapIndexInput(path="C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\MembersIndex\segments_eos")))
   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryCreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock, Directory& directory)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Umbraco.Cms.Infrastructure.Examine.ConfigurationEnabledDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass1_0.<.ctor>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location ---
   at System.Lazy`1.CreateValue()
   at Examine.Lucene.Providers.LuceneIndex.IndexReady()
   at Examine.Lucene.Providers.LuceneIndex.PerformIndexItemsInternal(IEnumerable`1 valueSets, CancellationToken cancellationToken)
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass50_0.<PerformIndexItems>b__0()
   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass75_0.<QueueTask>b__0(Task x)`

**Comment by readingdancer** [comment]
Hi @Shazwazza 

As always its much appreciated that you spend your time working on Examine, the last time the index failed for us was on Oct 7th and we had the following errors, you can see three different errors are being logged per request, we are catching all errors and pushing them to Slack, hence the screen shots, I hope it's useful:

![image](https://github.com/user-attachments/assets/20f5a397-14c6-4a4c-8d2a-fe7466d0c249)

**Stack Trace**
` at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)
   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)
   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
   at Umbraco.Cms.Infrastructure.Examine.ConfigurationEnabledDirectoryFactory.CreateDirectory...`

![image](https://github.com/user-attachments/assets/502cc2a7-4c0f-4bf3-9900-ff04f6a142a4)

**Stack Trace**
This is the same as the trace shown above.
   
![image](https://github.com/user-attachments/assets/ddc97809-e0a2-4045-af02-5addf13452c8)

**Comment by Shazwazza** [comment]
@kows the log message:

> "MembersIndex" index is corrupt, a new one will be created

is expected if in fact the index is corrupt. The log message is from here https://github.com/Shazwazza/Examine/blob/3e8bf11de0ecef7f77bbbb5cec14a095b37c7bfc/src/Examine.Lucene/Directories/SyncedFileSystemDirectoryFactory.cs#L224

When a new one is created and its empty, Umbraco will re-populate it but that doesn't kick in until a minute or two after site startup.

I'll revisit test cases, and add more scenarios until I can determine how to replicate in tests. Thanks for the info so far.

@readingdancer are you sure you have upgraded to 3.3.0? The stack trace you have provided doesn't show the stack that should be there, it should look like this on 3.3.0

```
at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)
at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)
at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryCreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock, Directory& directory)
at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
at Examine.Lucene.Directories.DirectoryFactoryBase.<>c__DisplayClass2_0.<Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory>b__0(String s)
```

Your stack trace only has

```
at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)
at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)
```

**Comment by Shazwazza** [comment]
@kows + @readingdancer  + everyone - some good news. I managed to replicate another issues which is fixed. I can't exactly replicate the one with the 'invalid deletion count' but I think it is directly related to the new fix.

I've published a beta here https://www.nuget.org/packages/Examine/3.3.1-beta.1

If anyone can please test, that would be great. This version will end up being 3.4.0 as it comes with performance improvements too and a small breaking change which reduces the default max results from 500 to 100 (if you need more, than use QueryOptions)

**Comment by Shazwazza** [comment]
That Lucene issue is only talking about the description of the error. Has anyone tested the beta release I mentioned above? Without feedback and testing, there is no way I can know if this is resolving the problem. In that case, I'll assume that no feedback means success and will publish the release.

**Comment by Shazwazza** [comment]
Examine 3.4.0 has been published https://github.com/Shazwazza/Examine/releases/tag/v3.4.0

**Comment by somoreingold** [comment]
@Shazwazza thanks!!!  I've had the beta running for a bit, but the nature of this issue is that it's very sporadic/intermittent. So I think only time will tell if your edits fixed it. Not sure if it's better to keep this issue open for a while, or close it and have people report again if the issue still persists. Thoughts?

**Comment by Shazwazza** [comment]
Sure, i think if folks can update to 3.4.0 and see how it goes, than report back here. With any luck maybe we can close this in November.

**Comment by tommilleruk** [comment]
Any update on this? We're experiencing the issue on Umbraco Cloud CMS Version 12.2.0

**Comment by Shazwazza** [comment]
@tommilleruk yes, see above. Upgrade to examine 3.4.0 and tell us how it goes.

**Comment by somoreingold** [comment]
Just upgraded today, I'll report back if i see issues. So far the only thing to note is making sure to change any code that may be affected by the described breaking change (default result total decreased to 100 max).

**Comment by binraider** [comment]
I have just pushed the 3.4 upgrade to production and it has not fixed the problem. I am thinking of changing the target azure webapps from windows to linux to see if that helps

**Comment by tommilleruk** [comment]
@Shazwazza It seems that upgrading Examine hasn't fixed this based on others comments. We are running our website using Umbraco Cloud so I don't think it's something we would have configured incorrectly?

**Comment by Shazwazza** [comment]
@tommilleruk are you saying this from experience or just from what someone else has posted? It definitely has fixed this, or derivations of this because it proves it in the tests that were created and written in Examine.

If you are actively seeing this issue with Examine 3.4.0, please post a stack trace of the issue and verify that you definitely have the 3.4.0 dll deployed.

**Comment by mbogunovic** [comment]
@Shazwazza this was solved from me even before the patches (I left a comment some time ago) and now with the Examine 3.5 as well (tried 3.4 as well).

So I would say that this thread is now overloaded with misconfigurations on specific projects since there are few things to configure in order to work properly...

Cheers!

**Comment by Shazwazza** [comment]
@mbogunovic thanks a bunch for the feedback. Maybe @bergmania, @nul800sebastiaan, or others may resolve this ticket? If there are existing/future issues, will be best they are opened on their own.

**Comment by markadrake** [comment]
Happened today,
Umbraco Cloud site,
upgrade to 13.6.0 and my indexes are corrupt.

I deleted the entire `umbraco/Data/TEMP/ExamineIndexes` folder via Kudu and restarted to get the indexes to rebuild.

**Comment by Shazwazza** [comment]
@markadrake stack trace please

**Comment by markadrake** [comment]
@Shazwazza I can supply some logs from Umbraco. Let me collect the distinct entries. I'll edit this comment with a link.

**Comment by PeterAtValantic** [comment]
I had this error last day as well. 
I am on Umbraco 13.5.3 and have updated all nuget packages and Examine package is on 3.6.0.
I am hosting on Azure as well. 

This is how my appsettings.json looks like:

` "Umbraco": {
    "CMS": {
      "RuntimeMinification": {
        "UseInMemoryCache": true,
      }, 
      "Global": {               
        "MainDomLock": "FileSystemMainDomLock"
      },     
      "Hosting": {
        "LocalTempStorageLocation": "EnvironmentTemp"
      },
      "Examine": {
        "LuceneDirectoryFactory": "SyncedTempFileSystemDirectoryFactory"
      }
    }`

This is the umbraco log file:
{
    "@t": "2025-02-03T11:55:04.0921069Z",
    "@mt": "{IndexName} index is corrupt, a new one will be created",
    "@l": "Error",
    "@x": "Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 (resource: BufferedChecksumIndexInput(SimpleFSIndexInput(path=\"C:\\home\\site\\wwwroot\\umbraco\\Data\\TEMP\\ExamineIndexes\\InternalIndex\\segments_1g1\")))\r\n   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)\r\n   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)\r\n   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)",
    "IndexName": "InternalIndex",
    "SourceContext": "Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory",
    "ProcessId": 2532,
    "ProcessName": "w3wp",
    "ThreadId": 12,  
    "Log4NetLevel": "ERROR"
}

So, how to solve this?

**Comment by Shazwazza** [comment]
@PeterAtValantic 

> So, how to solve this?

* Ensure that the Examine assembly deployed is in fact the latest version
* Open a new issue on the Examine repo https://github.com/shazwazza/Examine/
* Provide as much information as possible and potentially steps to replicate
  * Stack traces
  * What indexes get corrupt, 1, 2, all, etc... 
  * Any relevant config

Then... we need to figure out how to replicate this in an isolated test setup environment - just like I did for this exact issue already, but clearly there's some other strange way to continue to break the indexes.

See https://github.com/Shazwazza/Examine/blob/support/3.x/src/Examine.Test/Examine.Lucene/Directories/SyncedFileSystemDirectoryFactoryTests.cs

@markadrake all of your errors appear to be related to "Lucene.Net.Store.LockObtainFailedException" for the DeliveryApiContentIndex. This is a new one I haven't seen but considering the location reported: 

> lockFile 'C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\DeliveryApiContentIndex\write.lock' alredy exists.

That location indicates that this index is __not__ running on the local temp/fast drive and instead operating on the shared network drive. Please review your settings for "LuceneDirectoryFactory" for Azure hosting: 
* https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps
* https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps#lucene-examine-configuration

**Comment by PeterAtValantic** [comment]
For the one following this thread: we continue here https://github.com/Shazwazza/Examine/issues/402

**Comment by markadrake** [comment]
> That location indicates that this index is **not** running on the local temp/fast drive and instead operating on the shared network drive. Please review your settings for "LuceneDirectoryFactory" for Azure hosting:
> 
> * https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps
> * https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps#lucene-examine-configuration

Thank you for the info @Shazwazza! I'll give this a read through and see if there are details I can find specifically related to Umbraco Cloud. We happen to be using them to host this particular site. Thanks again mate!

**Comment by Shazwazza** [comment]
@PeterAtValantic actually now that I look further into your stack trace, this looks like the same problem as @markadrake...

> That location indicates that this index is not running on the local temp/fast drive and instead operating on the shared network drive. Please review your settings for "LuceneDirectoryFactory" for Azure hosting:

> https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/azure-web-apps
> https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/load-balancing/azure-web-apps#lucene-examine-configuration

This is the path of your index: 
C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\InternalIndex\

Which is not consistent with where it would exist if it were using the %temp% environment variable location.

**Comment by PeterAtValantic** [comment]
@Shazwazza 

So what setting should I use then?

https://docs.umbraco.com/umbraco-cms/reference/configuration/examinesettings
Default - The index will operate from the default location: umbraco/Data/TEMP/ExamineIndexes

SyncedTempFileSystemDirectoryFactory - The index will operate on a local index created in the processes %temp% location and will replicate back to main storage in umbraco/Data/TEMP/ExamineIndexes

TempFileSystemDirectoryFactory - The index will operate only in the processes %temp% directory location

The one I use now is the "SyncedTempFileSystemDirectoryFactory". 

Note: I am **not** on a load balanced server

This is our first project on Azure, so any tips and tricks about any config would be appreciated :)

**Comment by Shazwazza** [comment]
Thanks for the info @PeterAtValantic,

Sounds like its correct, if not load balancing and on azure then SyncedTempFileSystemDirectoryFactory is right. I realized that even though your stack trace shows files in the network file system, it could be because the directory also needs to open those files to do its replication. Happy to continue the chat/investigation on the Examine ticket. Note, i'm away next week so if I don't respond before then, that is why.

**Comment by protherj** [comment]
> The one I use now is the "SyncedTempFileSystemDirectoryFactory".
> 
> Note: I am **not** on a load balanced server

Do you happen to use Deployment slots or have any other instances pointing to your live DB in any way (failover or blue/green) setup?  That could mean that you technically are in a load balanced setup unintentionally.  Not sure if that would have an effect in this case however, but could result in locks I think.

**Comment by PeterAtValantic** [comment]
> Do you happen to use Deployment slots or have any other instances pointing to your live DB in any way (failover or blue/green) setup? That could mean that you technically are in a load balanced setup unintentionally. Not sure if that would have an effect in this case however, but could result in locks I think.

No, I use Visual Studio 2022 Publish to Azure to deploy the code and don't use any Deployment slots and the app is the only application who points to the Database.

**Comment by AdTarling** [comment]
We also experience this issue in our load balanced environment (Umbraco 13 currently, but seen on 7,9,10,13), albeit infrequently.
As per the load balanced docs (please see below) we have the scheduling publisher box (single instance) set as 'SyncedTempFileSystemDirectoryFactory' and subscriber box (load balanced instance) set as 'TempFileSystemDirectoryFactory'

<img width="468" alt="Image" src="https://github.com/user-attachments/assets/8b74a51f-df66-4973-8ce1-4cd4fbe47585" />

The issue seems to occur sometimes when our overnight data importers that consume external API data and then need to update Umbraco's content interact with one of the scheduled publisher indexes, which seems to have got itself into an unrecoverable state.  When this occurs I have to manually delete the indexes from the temp folder on the server and restart.  Example log:
`{"@t":"2025-03-09T02:25:04.9882276Z","@mt":"{IndexName} index is corrupt, a new one will be created","@l":"Error","@x":"Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 (resource: BufferedChecksumIndexInput(MMapIndexInput(path=\"C:\\home\\site\\wwwroot\\umbraco\\Data\\TEMP\\ExamineIndexes\\MembersIndex\\segments_28c\")))\r\n   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)\r\n   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)\r\n   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)","IndexName":"MembersIndex","SourceContext":"Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory","ProcessId":8276,"ProcessName":"w3wp","ThreadId":29,"ApplicationId":"ea6c9907b5dfb977abd279e5dd977d85f29f78cb","MachineName":"wn1xsdwk0008SF","Log4NetLevel":"ERROR"}`

I have seen this on multiple installs on multiple versions of Umbraco, so has it ever been considered that if this occurs then there should be final line of defence coding to physically delete the Examine cache from the file system and force it to rebuild?  I know that there is code in place to try and create a new index, but when this issue occurs, the underlying cache seems to be beyond repair so requires deleting and rebuilding.

**Comment by somoreingold** [comment]
> We also experience this issue in our load balanced environment (Umbraco 13 currently, but seen on 7,9,10,13), albeit infrequently. As per the load balanced docs (please see below) we have the scheduling publisher box (single instance) set as 'SyncedTempFileSystemDirectoryFactory' and subscriber box (load balanced instance) set as 'TempFileSystemDirectoryFactory'
> 
> <img alt="Image" width="468" src="https://private-user-images.githubusercontent.com/9961952/420940710-8b74a51f-df66-4973-8ce1-4cd4fbe47585.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE2MTY4MTAsIm5iZiI6MTc0MTYxNjUxMCwicGF0aCI6Ii85OTYxOTUyLzQyMDk0MDcxMC04Yjc0YTUxZi1kZjY2LTQ5NzMtOGNlMS00Y2Q0ZmJlNDc1ODUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDMxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAzMTBUMTQyMTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWRhNWYyNTYyMDIxOTU3YTNjYTUyMGViNDFkNWM5Y2FiODNiYTcwMjRhNmJlMjViOGJlNWNhNDFmMDJiZDYyOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GgK1QbTlcVb9VejH6TCWjWUS4Q6MbcHvKXbf30Ctd6o">
> The issue seems to occur sometimes when our overnight data importers that consume external API data and then need to update Umbraco's content interact with one of the scheduled publisher indexes, which seems to have got itself into an unrecoverable state. When this occurs I have to manually delete the indexes from the temp folder on the server and restart. Example log: `{"@t":"2025-03-09T02:25:04.9882276Z","@mt":"{IndexName} index is corrupt, a new one will be created","@l":"Error","@x":"Lucene.Net.Index.CorruptIndexException: invalid deletion count: 2 vs docCount=1 (resource: BufferedChecksumIndexInput(MMapIndexInput(path=\"C:\\home\\site\\wwwroot\\umbraco\\Data\\TEMP\\ExamineIndexes\\MembersIndex\\segments_28c\")))\r\n at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)\r\n at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)\r\n at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)\r\n at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)\r\n at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)","IndexName":"MembersIndex","SourceContext":"Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory","ProcessId":8276,"ProcessName":"w3wp","ThreadId":29,"ApplicationId":"ea6c9907b5dfb977abd279e5dd977d85f29f78cb","MachineName":"wn1xsdwk0008SF","Log4NetLevel":"ERROR"}`
> 
> I have seen this on multiple installs on multiple versions of Umbraco, so has it ever been considered that if this occurs then there should be final line of defence coding to physically delete the Examine cache from the file system and force it to rebuild? I know that there is code in place to try and create a new index, but when this issue occurs, the underlying cache seems to be beyond repair so requires deleting and rebuilding.

I personally like this idea in general; we've had to do something similar to "self-heal" programmatically in this manner, but it would be nice if this last line of defense was more integrated in the package itself--if it makes sense and doesn't have unforeseen ripple effects.

**Comment by Shazwazza** [comment]
Good news everyone, Examine 3.7.0 has been released which should resolve this (again) https://github.com/Shazwazza/Examine/releases/tag/v3.7.0

**Comment by kristofferwebmind** [comment]
We installed version 3.70 and have had it on dev environment since March 20. Deployed to live environment on April 11 at 7 am, the site seemed fine during the day but it went down after business hours and the log is now again full of

Lucene.Net.Index.CorruptIndexException: invalid deletion count: 96 vs docCount=1 (resource: BufferedChecksumIndexInput(MMapIndexInput(path="C:\home\site\wwwroot\umbraco\Data\TEMP\ExamineIndexes\ExternalIndex\segments_2q4")))

**Comment by Shazwazza** [comment]
@kristofferwebmind tracked here https://github.com/Shazwazza/Examine/issues/411
See comment https://github.com/Shazwazza/Examine/issues/411#issuecomment-2779210126

**Comment by dawoe** [comment]
@Shazwazza  I have upgraded to Examine 3.7.1 and don't see this issue anymore.

I also created a PR to update Examine in Umbraco : https://github.com/umbraco/Umbraco-CMS/pull/19186

**Comment by AdTarling** [comment]
Could someone confirm if this is fixed on Umbraco version 13.8.0, or 13.9.2 as we're just about to move to this version, as we still see the indexes corrupting every few weeks.

For example this morning the internal index went, but it can equally be external or members:
{"@t":"2025-07-07T07:55:48.3659285Z","@mt":"An error occurred processing the index batch.","@l":"Error","@x":"Lucene.Net.Index.CorruptIndexException: invalid deletion count: 3 vs docCount=1 (resource: BufferedChecksumIndexInput(MMapIndexInput(path=\"C:\\home\\site\\wwwroot\\umbraco\\Data\\TEMP\\ExamineIndexes\\InternalIndex\\segments_8q\")))\r\n   at Lucene.Net.Index.SegmentInfos.Read(Directory directory, String segmentFileName)\r\n   at Lucene.Net.Index.IndexFileDeleter..ctor(Directory directory, IndexDeletionPolicy policy, SegmentInfos segmentInfos, InfoStream infoStream, IndexWriter writer, Boolean initialIndexExists)\r\n   at Lucene.Net.Index.IndexWriter..ctor(Directory d, IndexWriterConfig conf)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.GetIndexWriter(Directory mainDir, OpenMode openMode)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryGetIndexWriter(OpenMode openMode, Directory luceneDirectory, Boolean createNewIfCorrupt, String indexName, IndexWriter& indexWriter)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.TryCreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock, Directory& directory)\r\n   at Examine.Lucene.Directories.SyncedFileSystemDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)\r\n   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)\r\n   at Umbraco.Cms.Infrastructure.Examine.ConfigurationEnabledDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)\r\n   at Examine.Lucene.Directories.DirectoryFactoryBase.Examine.Lucene.Directories.IDirectoryFactory.CreateDirectory(LuceneIndex luceneIndex, Boolean forceUnlock)\r\n   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass1_0.<.ctor>b__0()\r\n   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)\r\n--- End of stack trace from previous location ---\r\n   at System.Lazy`1.CreateValue()\r\n   at Examine.Lucene.Providers.LuceneIndex.PerformIndexItemsInternal(IEnumerable`1 valueSets, CancellationToken cancellationToken)\r\n   at Examine.Lucene.Providers.LuceneIndex.<>c__DisplayClass75_0.<QueueTask>b__0(Task x)","SourceContext":"Examine.Lucene.Providers.LuceneIndex","ProcessId":6820,"ProcessName":"w3wp","ThreadId":49,"ApplicationId":"ea6c9907b5dfb977abd279e5dd977d85f29f78cb","MachineName":"WN0XSDWK000806","Log4NetLevel":"ERROR"}

When Examine gets itself into this state the only fix is to delete the index folders, restart the Azure servers (scheduled publisher and subscriber) and rebuild.

Is it not possible to catch this exception: Lucene.Net.Index.CorruptIndexException and physically delete the examine folders and call it to rebuild itself?

I've cited this thread to a client as an attempt for us to mitigate the issue, but it's not ideal as either:
 - the external index corrupts which plays a part in rebuilding part of our ecommerce site data
 - the internal index corrupts, meaning the client can't search in umbraco
 - the members index corrupts, meaning the customer aspect of out ecommerce site is blocked from updating

It feels like Azure plays a role in it, especially when it switches virtual machines.  However, it can't be as simple as that as mostly we don't see the issue, just every 6 weeks or so.

**Comment by kristofferwebmind** [comment]
@AdTarling Umbraco 13.9.2 does target Examine 3.7.1, we have not seen index corruption issues yet since it was rolled out on June 24.

**Comment by AdTarling** [comment]
Ok, thanks @kristofferwebmind, I'll keep it monitored when we release again at the end of July.

**Comment by Shazwazza** [comment]
@AdTarling you can just update to the latest Examine version yourself, you don't need to wait to upgrade Umbraco.
