### ISSUE TITLE
V14-RC3: Culture variant page history shows TODO

### ISSUE THREAD

**Issue by PerplexDaniel** [umbraco/Umbraco-CMS#16293]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0-rc3

### Bug summary

When saving or publishing a page that can vary by culture the History UI shows TODO labels. 
This is highly unexpected for a Release Candidate.

### Steps to reproduce

1. Create a document type with "Allow vary by culture" enabled
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/d8a74734-4b71-43cf-942a-15b08dd19a06)
2. Create a node in the Content tree based on that doctype.
3. Save or publish the node
4. Observe Info > History contains `TODO` labels.
![image](https://github.com/umbraco/Umbraco-CMS/assets/24297947/a8927757-d60a-4a95-b551-e9020d1df784)

### Expected result / actual result

`TODO` labels in a Release Candidate are very unexpected.

**Comment by iOvergaard** [comment]
Thanks for testing. This has been fixed in RC4!

**Comment by OwainJ** [comment]
> Thanks for testing. This has been fixed in RC4!

Hi @iOvergaard, it's still an issue in RC4, also it looks like the variant versions of the statuses are missing the appropriate colours (they're all dashed red):
![image](https://github.com/umbraco/Umbraco-CMS/assets/17008780/ec9b4b9c-946d-4584-ab34-6ab172ab9626)

**Comment by PerplexDaniel** [comment]
@iOvergaard Please reopen this issue. Thanks for checking this in RC4 @OwainJ 👍
