### ISSUE TITLE
Umbraco slider ignores initial value property.

### ISSUE THREAD

**Issue by PryAl** [umbraco/Umbraco-CMS#17099]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.2.0

### Bug summary

I've created new slider controll and settes all defaults values:

![image](https://github.com/user-attachments/assets/2da79cea-1d40-41da-95a2-5d4b428e4926)

Despite the fact that the initial value is 6, the model returns 0 after the page is published.

If the editor changes the value to any value after publishing and publishes again, the value appears.

I saw that the same situation was relevant in previous versions (https://github.com/umbraco/Umbraco-CMS/issues/3855), and it seems to be still there.

### Steps to reproduce

1. Add slider to any property.
2. Set "Initial value".
3. Publish page with this slider.
4. Check initial value in the model.

### Expected result / actual result

Initial value should be present after first publish.

**Comment by NguyenThuyLan** [comment]
When click Save and Publish, the data sent does not have the default value of slide property
<img width="940" alt="image" src="https://github.com/user-attachments/assets/17614ab3-6e46-44e1-a6e6-6ea177fd7e7b">

**Comment by nikolajlauridsen** [comment]
Fixed in #17854, thanks for reporting 😄

**Comment by thenexus00** [comment]
This does not appear to be fixed. In Umbraco 15 Slider default values are still not passed and output as 0 until an interaction occurs on the slider in the backoffice.

This also appears to be an issue that has existed since Umbraco 7.

**Comment by NikiSkaarup** [comment]
Can confirm it is still an issue in v15.4.3

**Comment by AndyButland** [comment]
The original fix above was reverted as it was decided this should be handled client-side in the backoffice, and a resolution implemented using a [property value preset](https://docs.umbraco.com/umbraco-cms/customizing/extending-overview/extension-types/property-value-preset).  This is in place so I was confused as to why this was being reported as not working as expected.  I believe I can see the issue:

- The property value preset runs and works as expected when new content is created.  I've verified this - created a new document with a slider and an initial value, not touched the slider and published the page,  I see the slider value as expected when the template is rendered.
- But it doesn't run if the document already exists, a new slider property is added to it displaying the default value and the document is saved and published without touching the slider.  In other words, the property value presets are only activated on the scaffolding of new content, not on the addition of properties to existing content.

So I can see why this is and it is expected, but maybe we need to consider if we can support the second scenario here.  // @nielslyngsoe @kjac

**Comment by NikiSkaarup** [comment]
I looked at it some more it looks like when `Range` is not enabled it requires `initVal1` and `initVal2` to be set to the same value otherwise it fails validation with an unexpected range error

if you set `initVal1` to `10` and `range` is disabled, and `initVal2` is `0` you get the `unexpectedRange` error on value `10,0` if you don't change the value in the slider before pressing save and publish

**Comment by thenexus00** [comment]
> The original fix above was reverted as it was decided this should be handled client-side in the backoffice, and a resolution implemented using a [property value preset](https://docs.umbraco.com/umbraco-cms/customizing/extending-overview/extension-types/property-value-preset). This is in place so I was confused as to why this was being reported as not working as expected. I believe I can see the issue:
> 
> * The property value preset runs and works as expected when new content is created.  I've verified this - created a new document with a slider and an initial value, not touched the slider and published the page,  I see the slider value as expected when the template is rendered.
> * But it doesn't run if the document already exists, a new slider property is added to it displaying the default value and the document is saved and published without touching the slider.  In other words, the property value presets are only activated on the scaffolding of new content, not on the addition of properties to existing content.
> 
> So I can see why this is and it is expected, but maybe we need to consider if we can support the second scenario here. // [@nielslyngsoe](https://github.com/nielslyngsoe) [@kjac](https://github.com/kjac)

This is not the behaviour I see in the latest version of 15.
When sliders are in a Grid Block element and I add the grid component and having a default value the output from the property as an int value is ALWAYS 0 regardless of the default value.

It actually extends further to even The tick checkbox as well for example.
If I make a property with a tickbox that is set to on by default the bool value regardless returns false.

It seems that with the new backoffice UI values for defaults are only used for the backoffice and not properly passed through the object to use.

**Comment by AndyButland** [comment]
I'm not seeing this on 16, so long as I create and publish new content in the backoffice - just to replay:

- Created a document type with a block list, and an element type available on that block list with a slider with an initial value
- Create a new page, add the block, save and publish without touching the slider.
- When the page is rendered I'm seeing the expected initial value of the slider.

**Comment by thenexus00** [comment]
> I'm not seeing this on 16, so long as I create and publish new content in the backoffice - just to replay:
> 
> * Created a document type with a block list, and an element type available on that block list with a slider with an initial value
> * Create a new page, add the block, save and publish without touching the slider.
> * When the page is rendered I'm seeing the expected initial value of the slider.

Not the backoffice.

When you set a default value the back office elements reflect that.
It is when you are fetching the data from the object. 

Regardless of the default state for a slider when you read the object in a view or class etc the value is always 0. It only updates when you interact with the slider, even if you put it on the original value.

Noticed that with a checkbox as well that is pre-ticked to yes, the value is false unless you toggle it on and off.
