### ISSUE TITLE
Document Type Allowed Child Nodes Sort Order

### ISSUE THREAD

**Issue by wicketbr** [umbraco/Umbraco-CMS#17220]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.3.0

### Bug summary

In Umbraco 14 you can select a document type, got to Structure, then rearrange the "Allowed child node types" to the desired order. I checked the cmsContentTypeAllowedContentType table and confirmed that the SortOrder column updates when I save. However, refreshing the page does not keep the items in the correct sort order and when adding content in the Create dialog, the "Create an item under..." list is also not sorted according to that sort order.

### Steps to reproduce

Go to the Settings area, select a Document Type, go to the Structure option and rearrange the "Allowed child node types" items to be in the desired order, then click Save. Refreshing that page reverts the items to the order they are listed in the cmsContentTypeAllowedContentType, ingoring the SortOrder column. The SortOrder is saving, but not being used.

### Expected result / actual result

I would expect that when I go to add a new item below a node using the Create dialog that those allowed items would be in the order I set. It seems like the returned items should be sorted by the SortOrder value.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/17260

**Comment by wicketbr** [comment]
While the fix did correct the sort order when viewing the document type, the sort order is still not correct when adding new nodes. For example, I have set the document sort correctly for my "Home Page" types, and they are now sorting correctly when viewing them in the BackOffice under Document Types. However, in the Content area when I go to add a new item under a Home Page type they items are not sorting correctly in that interface.

**Comment by wicketbr** [comment]
I know this is marked as closed, but it has only been partially fixed. The sorting was fixed when viewing document types, but not when adding documents in the content area.
