### ISSUE TITLE
V15 Link picker accepts null item

### ISSUE THREAD

**Issue by AaronSadlerUK** [umbraco/Umbraco-CMS#17411]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc2

### Bug summary

When you add a item via the link picker, if you leave all the fields empty it will continue to accept it.

![image](https://github.com/user-attachments/assets/9d679353-cb90-4feb-b496-b9e494a73d48)

![image](https://github.com/user-attachments/assets/e8400dae-95c5-4f3d-85df-b3a53791bf78)

This is not a valid case for the link picker.

### Steps to reproduce

Add a link with nothing selected in the modal

### Expected result / actual result

The link picker should not accept when an editor selects nothing in the modal.

In this case it should throw can error prompting the editor to select or enter an item.

---
_This item has been added to our backlog AB#45539_

**Comment by leekelleher** [comment]
Fixed in https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2521.

**Comment by nielslyngsoe** [comment]
This issue is still present — A 'fix' is not sufficient for this issue, the right solution is to implement proper Client Validation in this dialog. — This will be handled in the coming sprint.

**Comment by iOvergaard** [comment]
The UX has been improved with the merge of #17994 and it is now impossible for the user to end up in a scenario where they submit a **null** value. The PR will end up in 15.2.
