### ISSUE TITLE
Focal Point on ImageCropper not restored after refresh

### ISSUE THREAD

**Issue by cf-marc** [umbraco/Umbraco-CMS#17955]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.2

### Bug summary

The focal point on an Image Cropper can be set correctly, but after refreshing the node, the focal point is reset to the center. However, this is only a visual bug, as the saved focal point remains correct in the backend.

![image](https://github.com/user-attachments/assets/6a676094-f385-4f58-87ad-41f1547929e5)

### Steps to reproduce

1. Create a Document Type with an Image Cropper property.
2. Create a new node and set the focal point to the top-left corner. Save the document.
3. Refresh the node.
4. Observe that the focal point is reset to the center of the Image Cropper, instead of retaining the position set earlier.

### Expected result / actual result

After reloading, the focal point is restored to its correct position.

**Comment by NguyenThuyLan** [comment]
Hi @cf-marc , thank you for reporting this issue. I was able to reproduce it on v13.6.0-rc

**Comment by AndyButland** [comment]
I'm actually not able to reproduce this @NguyenThuyLan and @cf-marc - please see the following and let me know if I've missed something when you have been able to replicate.  I'm running from source using the latest `v13/dev` (which is a little beyond `13.6.0-rc2`.

https://github.com/user-attachments/assets/c8d816df-042a-49e2-8296-0d691c2a50ae

**Comment by NguyenThuyLan** [comment]
Hi @AndyButland , @cf-marc , it seems I made some mistake, I am not able to reproduce it on v13.6.0-rc2 as Andy too, it seems this issue was fixed. I think we can close this issue now

**Comment by cf-marc** [comment]
Hey @NguyenThuyLan 

I installed the Umbraco 13.6 today, but it seems there is still an issue with the Focal Point.
https://github.com/user-attachments/assets/795be01a-81d8-4507-9f03-ad61a3da0b8b

If I refresh the browser, the Focal Point is centered again. However, when I resize my browser window, the Focal Point jumps from the center back to its previous position.

It seems to be an issue with the tabs. When I move my Cropper to the first tab, the Focal Point is restored correctly.

**Comment by NguyenThuyLan** [comment]
Hi @cf-marc , you're right, thank you for your video. This is a bug with the focal point display, it is actually saved.
I was able to reproduce it on 13.6.0
