### ISSUE TITLE
When having required properties in a different tab tab is not highlighted during validation

### ISSUE THREAD

**Issue by krebil** [umbraco/Umbraco-CMS#18096]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.1.1

### Bug summary

I have a required property on another tab the validation error shows correctly on while on the tab but there is no indication that you should navigate to a tab to spot a validation error.

### Specifics

![Image](https://github.com/user-attachments/assets/1d40613e-f9ed-4321-847e-07c9403b25c2)

![Image](https://github.com/user-attachments/assets/8a464abf-a8eb-4b6f-ab75-f07773df6f4d)

### Steps to reproduce

Create a document type with several tabs and make a property mandatory on tab other than the leftmost.
Try saving a content node while on the leftmost tab without filling out the mandatory property

### Expected result / actual result

I expect a visual indicator as to where mandatory data is missing

**Comment by karlmacklin** [comment]
I'd like to add that if you also have a long list of properties on a single tab, the current notification is not really helpful and will possibly leave the person editing the document confused.

It would be a huge improvement if the notification could name the labels of the properties that are wrong/missing. Or something along those lines to nudge the editor in the right direction.

**Comment by NguyenThuyLan** [comment]
Issue has the same error: https://github.com/umbraco/Umbraco-CMS/issues/18417

**Comment by madsrasmussen** [comment]
I am happy to tell you this has been fixed 🥳

**Comment by karlmacklin** [comment]
And there was much rejoicing!

**Comment by sniffdk** [comment]
@madsrasmussen 
Unfortunately, this is still not fixed.
I've tested this in version 17.0.2 and 17.1.0 on an empty Umbraco installation with just two doctypes and two properties on two different tabs.

The attached video shows the problem.

https://github.com/user-attachments/assets/a07f39f9-1890-4e55-b9ef-6bd00f724c46

Do let me know, if you prefer that I open a new issue.

**Comment by AndyButland** [comment]
I spotted this myself @sniffdk - which I believe is a regression - that I've proposed a fix for in https://github.com/umbraco/Umbraco-CMS/pull/21595

**Comment by sniffdk** [comment]
@AndyButland ahh very nice, thanks a lot for the quick reply 🔥
