### ISSUE TITLE
MemberManager.IsLoggedIn utility doesn’t work correctly - It ignore the AuthenticationType

### ISSUE THREAD

**Issue by gcotterman** [umbraco/Umbraco-CMS#18186]
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.3

### Bug summary

We are on Umbraco Cloud with Umbraco version 13.5.3. We are on out-of-the-box instance of Umbraco Cloud using Public Access for our Dev and Staging environments while our Live website is completely open access to the public with login for backoffice. We are not restricting access to Dev and Staging beyond requiring user login/authentication to view the site and to access the backoffice. The problem/bug is that Public Access apparently clashes with the MemberManager utility causing basic methods such as GetCurrent Member Async() and IsLoggedin() to fail. With Public Access on the Umbraco Cloud GetCurrentMemberAsync() always returns Null whether there is a current Member or not, and IsLoggedin() always returns True whether a Member is logged in or not. On our Local development machines the MemberManager utility works correctly for these two methods. This problem is just with Dev and Staging in the Umbraco Cloud with Public Access.

**Comment by ronaldbarendse** [comment]
@gcotterman Thanks for reporting this, but please use the issue template and paste the actual text instead of a screenshot 😄

**Comment by gcotterman** [comment]
@ronaldbarendse Thanks for your response.  It looks like this issue has been moved to a new ticket number so I take it that it is now in the "issue template" that you are talking about, is that correct?  Please let me know if there is something more that you need for me to do with this issue.  By the way, you said to paste the actual text rather than a screenshot, the funny thing is that I originally pasted text from OneNote into the rich text box and for some reason it was then converted to an image.  This is the first that I have seen that happen and it sounds like it was not the wanted result.

**Comment by gcotterman** [comment]
Hi @bergmania, thanks for your response above and your sample code as a temporary fix for the issue.  As I look at the code I don't see how the code is solving the problem.  It looks like the code is checking to see if the User is authenticated but what we are needing from the MemberManager is whether the Member is authenticated, or in other words, whether the User is also a Member.  It seems that this comes down to distinguishing between Users and Members.  

For our cloud dev and staging environments anyone on the site will always be an authenticated User, this is required for access to the site.  The question becomes are they an authenticated Member with MemberManger.IsLoggedIn() and also what their member name is and roles, etc. 

Currently with MemberManger.IsLoggedIn() always being true and MemberManager.GetCurrentMemberAsync() always null it seems that it is not possible to get Member information.  It seems that the provided code determines the status of the User but doesn't give information about the Member.  I take it that AuthenticationType of Identity would refer to the type of authentication of the User?

Please let me know if I am mistaken or not clear with this.

**Comment by bergmania** [comment]
Hi @gcotterman.

I know the code can seem weird. The `HttpContext.User` contains both the Umbraco User and Umbraco Member, that's why we need to check for the authentication type. 

Umbraco do not support anyway to check if a member is also a user. I guess you will have to compare emails to do something like that. It is perfectly valid to sign in with two different emails, as user and member, respectively. 

Maybe there is multiple errors, but `MemberManger.IsLoggedIn()` always being `true` imake sense with the correct code, as there will always be a User.

`MemberManager.GetCurrentMemberAsync() `always null should only happen, if only the user is signed in, but that obviously needs to be verified when the other issue is resolved.

**Comment by nikolajlauridsen** [comment]
Just popping in to say that I'm looking at this, there are indeed multiple errors at hand here like @bergmania  mentions 😄 

But yes, the AuthenticationType is a good way to tell what identity you have, since the backoffice user has a specific authentication type `Constants.Security.BackOfficeAuthenticationType`

**Comment by nikolajlauridsen** [comment]
Fixed in #18206, thanks for reporting 👍

**Comment by wardlawj** [comment]
Don't want to be the bearer of bad news but it doesn't seem like the change in v13.7.0 fixes this issues on Umbraco Cloud. With Public Access disabled I'm still seeing the issue where the Umbraco Cloud identity is overriding the MemberManager methods for returning the current user and isLoggedIn etc.

@gcotterman are you still seeing the same issue?

**Comment by gcotterman** [comment]
@wardlawj I have done a basic check of membership functionality since our Umbraco Cloud development instance has been updated to v13.7.0 and as far as I can tell our use of MemberManager is now working as designed.  IsLoggedIn appears to be working correctly, recognizing whether the member is logged in or not independent of user login.  The member object that is coming back from the GetCurrentMemberAsync appears to be valid and operational.  The code is checking the Name property of this object and the value is what is expected.  Before the member object was null and the member always showed as logged in but it appears that neither of these are the case any more.

Just tested this on my local instance (localhost) and MemberManager appears to continuing to be working in the local environment as well.  Not seeing any of the previous problems in either environment.   Note that we don't have an operational live environment yet so I am unable to test there.

**Comment by wardlawj** [comment]
I have to make a groveling appoloy! We have a wrapper services around the MemberManager methods and I had changed the IsLoggedIn call to the one @bergmania had posted above to see it it worked whilst waiting for the release. I forgot it was in there.....

I've stripped it out and all is working perfectly. 

Thanks @nikolajlauridsen, @bergmania, @gcotterman for your hard work on getting this fixed!
