### ISSUE TITLE
Performance issues with Querying & Traversal

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#18869]
### Which Umbraco version are you using?

15.3

### Bug summary

I'm testing out Umbraco 15 by upgrading some existing databases that we're currently running on v13. I deliberately made same "nasty" queries to test out how the HybridCache works.

This specific project have a "Container" node and then somewhere around 2500 nodes underneath. I'm using `Descendants` on the container to get these nodes.

```
var nodes = container.Descendants<MyNodeType>()
```

The exact same code executes in 72ms on the latest Umbraco 13-release but takes around 1200ms on v15.3.

I tried to set the cache to load all content into memory:

```
"Cache": {
  "DocumentBreadthFirstSeedCount": 50000,
  "MediaBreadthFirstSeedCount": 50000        
},
```

By using the debugger I can see that there are 35602 items in the underlying `MemoryCache` of the `HybridCache`, but when I reload the page it makes 100s of requests to the database to fetch content. The quries looks like this:

```sql
exec sp_executesql N'SELECT [umbracoNode].[id] AS [Id], [umbracoNode].[uniqueId] AS [Key], [umbracoNode].[level] AS [Level], [umbracoNode].[path] AS [Path], [umbracoNode].[sortOrder] AS [SortOrder], [umbracoNode].[parentId] AS [ParentId], [umbracoNode].[createDate] AS [CreateDate], [umbracoNode].[nodeUser] AS [CreatorId]
, [umbracoContent].[contentTypeId] AS [ContentTypeId]
, [umbracoDocument].[published] AS [Published], [umbracoDocument].[edited] AS [Edited]
, [umbracoContentVersion].[id] AS [VersionId], [umbracoContentVersion].[text] AS [EditName], [umbracoContentVersion].[versionDate] AS [EditVersionDate], [umbracoContentVersion].[userId] AS [EditWriterId]
, [umbracoDocumentVersion].[templateId] AS [EditTemplateId]
, [pcver].[id] AS [PublishedVersionId], [pcver].[text] AS [PubName], [pcver].[versionDate] AS [PubVersionDate], [pcver].[userId] AS [PubWriterId]
, [pdver].[templateId] AS [PubTemplateId]
, [nuEdit].[data] AS [EditData]
, [nuPub].[data] AS [PubData]
, [nuEdit].[dataRaw] AS [EditDataRaw]
, [nuPub].[dataRaw] AS [PubDataRaw]
FROM [umbracoNode]
INNER JOIN [umbracoContent]
ON ([umbracoNode].[id] = [umbracoContent].[nodeId])
INNER JOIN [umbracoDocument]
ON ([umbracoNode].[id] = [umbracoDocument].[nodeId])
INNER JOIN [umbracoContentVersion]
ON (([umbracoNode].[id] = [umbracoContentVersion].[nodeId]) AND [umbracoContentVersion].[current] = @0)
INNER JOIN [umbracoDocumentVersion]
ON ([umbracoContentVersion].[id] = [umbracoDocumentVersion].[id])
LEFT JOIN [umbracoContentVersion] [pcver]
INNER JOIN [umbracoDocumentVersion] [pdver]
ON (([pcver].[id] = [pdver].[id]) AND ([pdver].[published] = @1))
ON ([umbracoNode].[id] = [pcver].[nodeId])
LEFT JOIN [cmsContentNu] [nuEdit]
ON (([umbracoNode].[id] = [nuEdit].[nodeId]) AND [nuEdit].[published] = @2)
LEFT JOIN [cmsContentNu] [nuPub]
ON (([umbracoNode].[id] = [nuPub].[nodeId]) AND ([nuPub].[published] = @3))
WHERE ((([umbracoNode].[nodeObjectType] = @4) AND ([umbracoNode].[trashed] = @5)))
AND (([umbracoNode].[uniqueId] = @6))
ORDER BY [umbracoNode].[level], [umbracoNode].[parentId], [umbracoNode].[sortOrder]',N'@0 int,@1 int,@2 int,@3 int,@4 uniqueidentifier,@5 int,@6 uniqueidentifier',@0=1,@1=1,@2=0,@3=1,@4='C66BA18E-EAF3-4CFF-8A22-41B16D66A972',@5=0,@6='D289A6FC-606B-4B2B-8B8E-B1F4665D871D'
```

I was expecting the content to be in the memory cache, maybe I'm missing something here or is this expected behavior?

UPDATE: 
Looked closer at `DocumentCacheService` and it seems like the problem here is that some nodes have unpublished parents which resolves to a null value that is not stored in the cache, so this lookup against the database is performed on each request.

![Image](https://github.com/user-attachments/assets/d8584044-8813-4c75-ba46-9e2a6b9c1870)

Tried to comment out the line that removes the stored null-values from the cache and after this the page load times goes from 1200ms to 130ms.

![Image](https://github.com/user-attachments/assets/ee47da45-fc6f-41e9-8817-55bab265d113)

---
_This item has been added to our backlog AB#51325_

**Comment by enkelmedia** [comment]
@nielslyngsoe might also be worth looking at: https://github.com/umbraco/Umbraco-CMS/issues/18892 at the same time as they are in the same area of the code and both contribute to the issue.

**Comment by Migaroez** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/19137

**Comment by enkelmedia** [comment]
Wow! Nice @Migaroez! I’ll give this a spin tomorrow or during the weekend and let you know.

**Comment by enkelmedia** [comment]
@Migaroez the same page loads in around 90-100ms when testing it on `v16/dev` so definitely a huge improvement! Really nicely done! 🚀

I still see that there are nodes requested that return null and hence there are still calls to the database on each page load, it's far less (only 4 calls now) so the problem is not 100% gone. This database has been around and upgraded from Umbraco 7 so it might be some inconsistencies in the database and content references.

![Image](https://github.com/user-attachments/assets/249fd85e-23d0-4171-902d-22b4b67a0901)

The four db-calls are in two "categories",

**1.**
First there is a request to a trashed node in the Recycle Bin, I guess that the query returns null because it probably does not have any "published" version.

**2.**
Then there are three calls that execute the exact same query, looking for this node `[umbracoNode].[uniqueId] = '55e2feb3-3da3-4219-9927-99549bd45beb'` that does not exist in the database.

The queries look like this:

```sql
SELECT [umbracoNode].[id] AS [Id], [umbracoNode].[uniqueId] AS [Key], [umbracoNode].[level] AS [Level], [umbracoNode].[path] AS [Path], [umbracoNode].[sortOrder] AS [SortOrder], [umbracoNode].[parentId] AS [ParentId], [umbracoNode].[createDate] AS [CreateDate], [umbracoNode].[nodeUser] AS [CreatorId]
, [umbracoContent].[contentTypeId] AS [ContentTypeId]
, [umbracoDocument].[published] AS [Published], [umbracoDocument].[edited] AS [Edited]
, [umbracoContentVersion].[id] AS [VersionId], [umbracoContentVersion].[text] AS [EditName], [umbracoContentVersion].[versionDate] AS [EditVersionDate], [umbracoContentVersion].[userId] AS [EditWriterId]
, [umbracoDocumentVersion].[templateId] AS [EditTemplateId]
, [pcver].[id] AS [PublishedVersionId], [pcver].[text] AS [PubName], [pcver].[versionDate] AS [PubVersionDate], [pcver].[userId] AS [PubWriterId]
, [pdver].[templateId] AS [PubTemplateId]
, [nuEdit].[data] AS [EditData]
, [nuPub].[data] AS [PubData]
, [nuEdit].[dataRaw] AS [EditDataRaw]
, [nuPub].[dataRaw] AS [PubDataRaw]
FROM [umbracoNode]
INNER JOIN [umbracoContent]
ON ([umbracoNode].[id] = [umbracoContent].[nodeId])
INNER JOIN [umbracoDocument]
ON ([umbracoNode].[id] = [umbracoDocument].[nodeId])
INNER JOIN [umbracoContentVersion]
ON (([umbracoNode].[id] = [umbracoContentVersion].[nodeId]) AND [umbracoContentVersion].[current] = 1)
INNER JOIN [umbracoDocumentVersion]
ON ([umbracoContentVersion].[id] = [umbracoDocumentVersion].[id])
LEFT JOIN [umbracoContentVersion] [pcver]
INNER JOIN [umbracoDocumentVersion] [pdver]
ON (([pcver].[id] = [pdver].[id]) AND ([pdver].[published] = 1))
ON ([umbracoNode].[id] = [pcver].[nodeId])
LEFT JOIN [cmsContentNu] [nuEdit]
ON (([umbracoNode].[id] = [nuEdit].[nodeId]) AND [nuEdit].[published] = 0)
LEFT JOIN [cmsContentNu] [nuPub]
ON (([umbracoNode].[id] = [nuPub].[nodeId]) AND ([nuPub].[published] = 1))
WHERE ((([umbracoNode].[nodeObjectType] = c66ba18e-eaf3-4cff-8a22-41b16d66a972) AND ([umbracoNode].[trashed] = 0)))
AND (([umbracoNode].[uniqueId] = 55e2feb3-3da3-4219-9927-99549bd45beb))
ORDER BY [umbracoNode].[level], [umbracoNode].[parentId], [umbracoNode].[sortOrder]
```

Looking at the stack trace it's some old reference to this node from a MultiNodeTreePicker, so probably someone referenced the node in a picker and then removed it - not a super-uncommon scenario.

![Image](https://github.com/user-attachments/assets/ab272b84-110b-410d-bc8b-322b2e5f6dc3)

I traced this down to a MultiNodeTree picker that was pointing to this removed node from three other nodes that was loaded on the test-page (the specific property was never used/read). This could be a potential issue in code that generate menus etc. if there are one or more pickers with references to removed content it would result in db-calls on each page load.

The fact that the same call is not even cached within the same request is more related to my other issue https://github.com/umbraco/Umbraco-CMS/issues/18892.

I did notice however, that the stored value in the db looks like this:

![Image](https://github.com/user-attachments/assets/1ee410b1-6c09-49f9-b178-b8d2f82a5776)

The backoffice would call `umbraco/management/api/v1/item/document?id=55e2feb3-3da3-4219-9927-99549bd45beb&id=ba021a96-e60e-41b4-a091-183fee135d7b` to get the nodes, but the returned value would only contain the one that was found:

```
[
    {
        "isTrashed": false,
        "isProtected": false,
        "parent": {
            "id": "f18033c6-eaef-4099-8621-c73e3e345329"
        },
        "hasChildren": false,
        "documentType": {
            "id": "080a0095-fb93-7cd7-b0ca-93db01425068",
            "icon": "icon-molecular",
            "collection": null
        },
        "variants": [
            {
                "state": "Published",
                "name": "V.......",
                "culture": null
            }
        ],
        "id": "ba021a96-e60e-41b4-a091-183fee135d7b"
    }
]
```

This means that the MultiNodeTree-picker UI would only show one item, the old `this item has been removed`-indicator does not work because of this (probably also another issue).

![Image](https://github.com/user-attachments/assets/7085a93c-4611-4ceb-bcb6-39892e5c5ead)

Back to the "real" issue here,

I don't really follow the reasoning for not storing the null result in the cache, if the L2 cache can't handle a null value something else could be stored to represent that the node does not exist to avoid putting load on the db?

Again referencing the memory issues mentioned in https://github.com/umbraco/Umbraco-CMS/issues/18892, I think that maybe the in-memory representation and the serialized representation of a node needs to be different to avoid having a GC that goes crazy - but I do understand that would be a huge thing to take on.
