### ISSUE TITLE
v16: Time-only DateTime picker

### ISSUE THREAD

**Issue by Luuk1983** [umbraco/Umbraco-CMS#19865]
### Which Umbraco version are you using?

16.1.1

### Bug summary

I want to have a time-only property editor. Everything in the backoffice facilitates this and you even get a nice time-only picker, but it will throw an error when saving.

### Steps to reproduce

Create a time data type using the Date Picker Property Editor UI and supply a date format of HH:mm:

<img width="1415" height="444" alt="Image" src="https://github.com/user-attachments/assets/46fb2cee-fe6d-4cf0-8748-ddac471982a7" />

When you use that data type on your content type, it actually displays a very nice time selector that even has a clock instead of a calendar icon:

<img width="451" height="135" alt="Image" src="https://github.com/user-attachments/assets/cd6eeec8-47fc-40f5-afa8-00ec438b4c7b" />

It even supports the pickers to select the time:

<img width="371" height="316" alt="Image" src="https://github.com/user-attachments/assets/212e5640-447d-4f6f-a630-af924bbd7e98" />

Awesome, that's exactly when I want! However when saving....

<img width="400" height="106" alt="Image" src="https://github.com/user-attachments/assets/204d658e-f481-4df7-9339-b14af3764058" />

And it's the obvious error I expected:
System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.

### Expected result / actual result

I guess it's a scenario that wasn't considered, but since it works so well to have a time-only property editor, it's a real shame it cannot be used. I think this should be fixed one of two ways:

* Support the time-only version (can't we use datetime2 in the database?)
* Or make sure that the date format on the property editor cannot be invalid. (In which case I need to make a custom data editor for time-only myself...).

---
_This item has been added to our backlog AB#55868_

**Comment by NguyenThuyLan** [comment]
Thank you @Luuk1983 , I was able to reproduce it on v16.1.1.
This issue occurs when using SQL Server, but did not occur when using SQLite.

**Comment by NillasKA** [comment]
Resolved for 16.3 in https://github.com/umbraco/Umbraco-CMS/pull/20019

**Comment by thomashdk** [comment]
Still getting the error in Umbraco 17.6.1


`System.Data.SqlTypes.SqlTypeException: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.
   at System.Data.SqlTypes.SqlDateTime.FromTimeSpan(TimeSpan value)
   at Microsoft.Data.SqlClient.MetaType.FromDateTime(DateTime dateTime, Byte cb)
   at Microsoft.Data.SqlClient.TdsParser.WriteUnterminatedValue(Object value, MetaType type, Byte scale, Int32 actualLength, Int32 encodingByteSize, Int32 offset, TdsParserStateObject stateObj, Int32 paramSize, Boolean isDataFeed)
   at Microsoft.Data.SqlClient.TdsParser.TDSExecuteRPCAddParameter(TdsParserStateObject stateObj, SqlParameter param, MetaType mt, Byte options, SqlCommand command, Boolean isAnonymous)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, IList`1 rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at NPoco.Database.UpdateBatchAsyncImp[T](IEnumerable`1 pocos, BatchOptions options, Boolean sync, CancellationToken cancellationToken)
   at NPoco.Database.UpdateBatchAsyncImp[T](IEnumerable`1 pocos, BatchOptions options, Boolean sync, CancellationToken cancellationToken)
   at NPoco.Database.UpdateBatch[T](IEnumerable`1 pocos, BatchOptions options)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.ContentRepositoryBase`3.ReplacePropertyValues(TEntity entity, Int32 versionId, Int32 publishedVersionId, Boolean& edited, HashSet`1& editedCultures)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.DocumentRepository.PersistUpdatedItem(IContent entity)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Update(TEntity entity, Action`1 persistUpdated)
   at Umbraco.Cms.Core.Services.ContentService.CommitDocumentChangesInternal(ICoreScope scope, IContent content, EventMessages eventMessages, IReadOnlyCollection`1 allLangs, IDictionary`2 notificationState, Int32 userId, Boolean branchOne, Boolean branchRoot, Boolean raiseSavedNotification)
   at Umbraco.Cms.Core.Services.ContentService.SaveAndPublish(IContent content, String[] culturesToPublish, Int32 userId)
   at Umbraco.Cms.Core.Services.ContentEditingService.SaveAndPublish(IContent content, String[] culturesToPublish, Guid userKey)`
