### ISSUE TITLE
After Logout (timout) login redirect not working

### ISSUE THREAD

**Issue by croban** [umbraco/Umbraco-CMS#19971]
### Which Umbraco version are you using?

13.10.0

### Bug summary

Login into Umbraco
Wait to be logged out
Login again 
Redirect goes to homepage :(

Edge lts

### Steps to reproduce

Login into Umbraco
Wait to be logged out
Login again 
Redirect goes to homepage :(

Edge lts

### Expected result / actual result

To go back where I left before session timeout.

---
_This item has been added to our backlog AB#55979_

**Comment by leekelleher** [comment]
Fixed in #19984 for v13.11.0.

**Comment by umbracocommunity** [comment]
This issue has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/v13-10-login-redirect/6009/2

**Comment by jose-lopez1** [comment]
I have upgraded to 13.11.0, but I'm still seeing the same issue. Anyone else?
