### ISSUE TITLE
Tree collapses when accessing a node via URL or refreshing the node

### ISSUE THREAD

**Issue by ppsyrra** [umbraco/Umbraco-CMS#20419]
### Which Umbraco version are you using?

16.2.0

### Bug summary

Tree list collapses every time a page is refreshed or when opening a URL that contains a node. 

### Steps to reproduce

Case 1: 

1. Go to Umbraco v16.2.0 BO
2. Open any child tree node 
3. Refresh the page
4. The tree collapses

Case 2: 

1. Copy a URL of a child tree node
2. Open new tab and paste it
3. Node content on the right is visible but the tree is collapsed 

[Tree collapse.zip](https://github.com/user-attachments/files/22763860/Tree.collapse.zip)

### Expected result / actual result

Expected: Tree is expanded and is highlighting the child node

**Comment by AndyButland** [comment]
I think you'll find this has been resolved in 16.3, which is out as a release candidate now if you'd like to check it out.

**Comment by Didier-Marin** [comment]
I just did a test with 16.3.0 RC4 and it's not fixed; the tree still collapses after refreshing the page. The same with accessing the node directly via the url

**Comment by AndyButland** [comment]
Maybe we are talking cross-purposes - this is what I see on a clean install of 16.3.0-rc4.  I've just added a single doc type, allowed at root and under itself, and made a few content items.

https://github.com/user-attachments/assets/0c35780e-929e-4640-b013-b872a73c2958

Are you seeing otherwise or am I looking in the wrong place?

**Comment by simonechGSC** [comment]
@AndyButland indeed, with a clean installation it works with the RC.
But still not in our project... we'll dig and see if we can spot the reason, maybe it's the multiple root nodes or the 1000+ nodes and multiple levels in the tree.
I don't think we have extended anything related to tree rendering.
(damn, wrong user :) I'm @simonech
