### ISSUE TITLE
'Create' options no indication it's loading when it's slow

### ISSUE THREAD

**Issue by Luuk1983** [umbraco/Umbraco-CMS#20817]
### Which Umbraco version are you using?

16.3.4

### Bug summary

The 'Create' menu, which shows a list of all possible content types you can create a node for is sometimes really slow to load. But there is no indication that it's loading.

### Specifics

I have a long 'create' menu and sometimes it's a bit slow. Now that is not the issue I'm raising here, because it happends sometimes when the cache hasn't been properly loaded or when I'm in debug mode.

However, there is no feedback that the create menu is loading at all. It just shows the message that there are no allowed document types:

<img width="513" height="377" alt="Image" src="https://github.com/user-attachments/assets/717f95b0-f673-4306-b60d-9b4d00ea413c" />

When it's slow, it sometimes takes 10 seconds to load the menu and even I as a developer have wondered a few times if I broke something, only for it suddenly pop up with to the correct options:

<img width="493" height="980" alt="Image" src="https://github.com/user-attachments/assets/8ad9e8b3-7f5c-4564-971e-53311314837f" />

I usually tend to forgive small UX things because I know it will get better. However, in this case, it's really bad design. If I got caught out by this a few times, editors definitely will as well.

### Steps to reproduce

-

### Expected result / actual result

Ideally, the create menu should never be slow, but when it is (when the cache is not yet loaded, bad network conditions etc), it should at least show a loading message or icon instead of the message that there are no document types that can be created.

**Comment by NguyenThuyLan** [comment]
Same problem in v17.0.0-rc2

**Comment by nielslyngsoe** [comment]
We in general have not been good at implementing loaders, this should be farily available to implement and therefor I marked this as up-for-grabs.

Its a good first timer contribution, so if you like to learn how to do things in the new front-end of Umbraco then this is a good specific task to resolve.

**Comment by nielslyngsoe** [comment]
Fixed by https://github.com/umbraco/Umbraco-CMS/pull/20857 will be part of v.17.1

**Comment by bgraham123** [comment]
Hi I'm still seeing this in 17.3.3. I've created a discussion [here](https://github.com/umbraco/Umbraco-CMS/discussions/22473).  Can we reopen this issue? @Luuk1983
