### ISSUE TITLE
Media uploader in RTE doesn't select uploaded image

### ISSUE THREAD

**Issue by JorickDJ** [umbraco/Umbraco-CMS#3022]
This issue was already submitted on 12th of September 2017 and we are still having problems with this issue in Umbraco version 7.10.5.

The previous bug submission can be found here:
https://issues.umbraco.org/issue/U4-10408

When I want to add a new image to the RTE I click on the Image Picker and upload a new image. The Image Picker indicates that the image is selected and when you click "Submit" it adds a "nothing.jpg" to the RTE.

If you upload a new image in the RTE Image Picker and then scroll to the uploaded image and select it again, then it will be added correctly.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/3117

**Comment by jannikanker** [comment]
@KimHolzmann @nul800sebastiaan I'm still seeing this happen in 7.12.4 :-s Also the browse dialog seems to pop up three times, seemingly unmotivated (although that might be an entirely different issue).

Any idea what is happening?

![3022](https://user-images.githubusercontent.com/1769849/57017787-f1068380-6c20-11e9-850c-6c4944ecce05.gif)

**Comment by KirschnerMatt** [comment]
This is still happening on a fresh install of 7.15.3

**Comment by enkelmedia** [comment]
Same here!

**Comment by enkelmedia** [comment]
One idea, at least is to ship the "nothing.jpg"-image so that the editors can see that something went wrong.

**Comment by jannikanker** [comment]
@nul800sebastiaan Might there be grounds for reopening this case? I know full well that I reported it using an older version than the fix, but people seem to still be experiencing it in the latest (v7) version :-/

**Comment by nul800sebastiaan** [comment]
Create a new issue for it please, whatever was fixed in this PR is what this issue is marking, apparently there's something else / additional wrong or it wasn't fixed properly. We can't re-open issues that have a release tag on them. :)
