### ISSUE TITLE
multinode treepicker

### ISSUE THREAD

**Issue by JayCoady34** [umbraco/Umbraco-CMS#3073]
Multinode Treepicker crashes the site if an item picked in it is deleted at the source(not just removed from the picker). I would expect a null to be returned like the Media picker but that isn't the case.

### Specifics

We are using version 7.11.1
This is not a browser issue but I've tested in on most recent versions of Chrome, Edge and Firefox

File generating error, lines and exception being thrown are below

App_Data\Models\CarouselItem.generated.cs

public IEnumerable<IPublishedContent> Price
{
get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("price"); }
}

[NotSupportedException: Cannot access this method unless the Umbraco membership provider is active]
   Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem) +362
   Umbraco.Core.Cache.CacheProviderExtensions.GetCacheItem(ICacheProvider provider, String cacheKey, Func`1 getCacheItem) +171
   Umbraco.Web.UmbracoHelper.TypedMember(Udi id) +96
   Umbraco.Web.PropertyEditors.ValueConverters.MultiNodeTreePickerPropertyConverter.GetPublishedContent(T nodeId, UmbracoObjectTypes& actualType, UmbracoObjectTypes expectedType, Func`2 contentFetcher) +53
   Umbraco.Web.PropertyEditors.ValueConverters.MultiNodeTreePickerPropertyConverter.ConvertSourceToObject(PublishedPropertyType propertyType, Object source, Boolean preview) +1083
   Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedProperty.get_Value() +109
   Umbraco.Web.PublishedPropertyExtension.GetValue(IPublishedProperty property, Boolean withDefaultValue, T defaultValue) +117
   Umbraco.Web.PublishedContentExtensions.GetPropertyValue(IPublishedContent content, String alias) +75
   Umbraco.Web.PublishedContentModels.CarouselItem.get_Price() in D:\WRK\E-Photo 3.0\Developpement\Web\Order\Application\Ephoto-Umbraco\EphotoUmbraco\App_Data\Models\CarouselItem.generated.cs:81
   EphotoUmbraco.Controllers.ImageController.GetHomeCarouselItems(IPublishedContent carousel) in D:\WRK\E-Photo 3.0\Developpement\Web\Order\Application\Ephoto-Umbraco\EphotoUmbraco\Controllers\ImageController.cs:230
   EphotoUmbraco.Controllers.ImageController.ProductsCarousel(Boolean isHome, Boolean isBlacks) in D:\WRK\E-Photo 3.0\Developpement\Web\Order\Application\Ephoto-Umbraco\EphotoUmbraco\Controllers\ImageController.cs:81
   lambda_method(Closure , ControllerBase , Object[] ) +201
   System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters) +229
   System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters) +35
   System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState) +39
   System.Web.Mvc.Async.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult) +77
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() +72
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() +387
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +42
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +38
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +188
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +38
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +29
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +52
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +39
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +38
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +43
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +73
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +38
   System.Web.Mvc.<>c__DisplayClass4.<Wrap>b__3() +18
   System.Web.Mvc.ServerExecuteHttpHandlerWrapper.Wrap(Func`1 func) +29
   System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride) +1706

### Steps to reproduce

Create a Document Type with a multinode treepicker and create a page with it (page A).
Ours is set to have a maximum number of  1 item.
Create another test page B of any document type it doesn't matter.

Now in Page A use the treepicker to select Page B. Save and Publish.
Now Go to page B and delete it.
It will now appear grayed in Page A in the back-end.
If you try to access this property in your back-end now it will tell you it still has a value  but if you try and retrieve the value you will get an exception even though HasValue returns true.

The only way to fix this is to go into the back-end, empty the recycle bin, and Save and Publish Page A.
Republishing the entire site doesn't fix it.

### Expected result
I would expect HasValue to return false for this field and FirstOrDefault() to return null instead of crashing.

### Actual result

See exception above.

Everytime we use the multinode treepicker (and yes it's version2), which we do a lot, we have to put a try catch around it when getting a value rather than just checking for null

**Comment by JayCoady34** [comment]
This becomes even more problematic when the field in question was Mandatory. There should be a warning or popup preventing the user from deleting the node if it has been selected in a picker and is a mandatory field

**Comment by kjac** [comment]
I'm pretty sure this has been resolved in the latest version.

![image](https://user-images.githubusercontent.com/7405322/46336469-2ddaaf80-c62b-11e8-8f6b-d3cd4a80a595.png)

Given this simple template, I can't provoke the the issue neither in the backoffice or in the page rendering:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
	var nodes = Model.Content.GetPropertyValue<IEnumerable<IPublishedContent>>("nodes");
}
<h1>Number of nodes: @nodes.Count()</h1>
<ul>
@foreach(var node in nodes) {
    <li>@node.Name (@node.Id)</li>
}
</ul>
```

**Comment by JayCoady34** [comment]
I saw nothing in the release notes about fixing this bug, but we updated to most recent version to be sure and we are still having the issue.

![image](https://user-images.githubusercontent.com/15877252/46357958-ef95be00-c633-11e8-8b07-297e79e5dfb9.png)

**Comment by kjac** [comment]
@JayCoady34 That sounds funky indeed. I can't imagine why the two would have anything to do with one another.

Also when I'm testing using the template above I never get a `null` value. If no nodes are selected (or all the selected ones are in the trash) I get an empty collection; hence the `<h1>` rendering doesn't fail on a null reference for empty node pickers.

**Comment by kjac** [comment]
@JayCoady34 did you ever figure out that caused this? Or in other words - is this issue still relevant?

**Comment by nul800sebastiaan** [comment]
I'll close this since it seems to have something to do with custom code, feel free to discuss this further on the forum if necessary!
