### ISSUE TITLE
Publish a variant without a name gives YSOD

### ISSUE THREAD

**Issue by madsrasmussen** [umbraco/Umbraco-CMS#3396]
child of https://github.com/umbraco/Umbraco-CMS/issues/3695

If you try to publish a variant without a name you get a YSOD. You should see a validation message instead.

**Comment by emmagarland** [comment]
@madsrasmussen not sure if this is the exact same issiue, but have just debugged and can replicate in temp8:

1. Create a content node (e.g. "general") with 1 language and no mandatory fields, save and publish
2. Setup a new language
3. Set the general doc type to be variable by language
4. Return to the node for that document type (e.g. "Page not found" of general doctype)
5. Click "Publish" in the original language view _before_  setting a node name on the new language for this node
6. Click to publish both languages 

![image](https://user-images.githubusercontent.com/1649855/48209667-9d9c3280-e36d-11e8-830e-b39bd1101273.png)


7. Observe error

![image](https://user-images.githubusercontent.com/1649855/48210155-b48f5480-e36e-11e8-985e-587ca8432d33.png)


The name of the node for that language variant is null, and the code ends up throwing an InvalidOperationException because the published state is "Publishing" (ContentService.cs "Save" method,  line 768). 

If you switch to the new language view, you aren't able to save and publish because the validation of the empty name kicks in.

Speaking to @nul800sebastiaan and testing by adding a mandatory field on the second language and not filling it out, you get a validation error. Perhaps we could apply the same client-side validation logic for no name as well (as per below)?:

![image](https://user-images.githubusercontent.com/1649855/48209919-38950c80-e36e-11e8-9397-f94fdf8f05b2.png)

**Comment by jobf** [comment]
There is client side validation already happening to check for the node Name but it only checks the variant that is visible on screen.  

For example if you have the variants in split-view 
![image](https://user-images.githubusercontent.com/22012032/48211013-7d21a780-e370-11e8-87dd-33d4c87a3bd7.png)

**Comment by clausjensen** [comment]
I believe this has been fixed. I'm able to get a clientside validation error directly in the publish dialog if I haven't specified a name for a variant - even though the variant is not currently being shown in the UI.

**Comment by nielslyngsoe** [comment]
This issue is still present, at least in some format.

Way to replicate:
1. Create a docType that can are allowed to varying by culture.
2. Create a content node of this type.
3. Enter a name for the default language.
4. click Save & publish and choose the other language as well.

Then you will get this screen, not a visual validation error:
![image](https://user-images.githubusercontent.com/6791648/51596040-5a774780-1ef8-11e9-971f-f4ac27044fd4.png)

**Comment by bergmania** [comment]
PR: https://github.com/umbraco/Umbraco-CMS/pull/4228
