### ISSUE TITLE
Existing Views Are Overwritten When Creating a New Template

### ISSUE THREAD

**Issue by 0Neji** [umbraco/Umbraco-CMS#3494]
I'm looking to set up some content types programatically and have run into a problem. I'd like to initialize new templates within my code but also have them exist as a file in the project from the start.

### Bug summary

When creating a new template via code, if a view exists with the same name, it is overwritten. I believe there should be a check in place that if the view exists, it's left alone but the template is added to the database regardless. If the file doesn't exist, only then should it create a new, blank one.

### Specifics

Umbraco version: 7.12.3

### Steps to reproduce

1. Create a new view in `~\Views` called `Test.cshtml`. Enter some content, for example:

```
@{
    Layout = null;
}

<h2>Homepage</h2>
```

2. Create a start up event that creates a new template:

```
using System;
using Umbraco.Core;

namespace Umbraco.Baseline.Web.Events
{
    public class Started : ApplicationEventHandler
    {
        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            UmbracoApplicationBase.ApplicationStarted += InitialiseTemplates;
        }

        private void InitialiseTemplates(object sender, EventArgs eventArgs)
        {
			ITemplate template = _fileService.GetTemplate("test");

            if (template == null)
            {
                template = new Template("Test", "test");

                _fileService.SaveTemplate(template);
            }
        }
    }
}
```

3. See that `Test.cshtml` has been overwritten by a basic Umbraco template view:
```
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
```

### Expected result

When the template is saved, existing views with the same name aren't overwritten.

### Actual result

A blank/basic view is written into the contents of the view in the place of already existing content.

I'm not sure if there's reasoning behind this behaviour but nothing jumps to mind so I believe this to be a bug. I believe this also used to happen when creating templates in the CMS, although I have a feeling this has been fixed.

I thought I'd just get a discussion going as to whether this should be fixed or not - if so, I'm happy to submit a PR to fix it but didn't want to go ahead with getting some sort of agreement first.

Thanks,

Ben

**Comment by nul800sebastiaan** [comment]
Thanks @0Neji This has been fixed for 7.13 already: https://github.com/umbraco/Umbraco-CMS/issues/3494

**Comment by 0Neji** [comment]
Hi @nul800sebastiaan,

Sorry to bring this back up. I'm still seeing the behaviour I outlined in my original post - even in Umbraco 8.0.1.

Just to be clear, my problem is when creating a template **programatically**, I've seen another issue where it's been fixed when creating a new template in the back office.

Would it be possible to recreate this and take another look at the issue please?

Thanks,

Ben
