### ISSUE TITLE
V8: Linkpicker misbehaves when editing a link

### ISSUE THREAD

**Issue by kjac** [umbraco/Umbraco-CMS#4083]
If you edit a link e.g. from an RTE, the link lists as "[object Object]":

![linkpicker-from-rte-before](https://user-images.githubusercontent.com/7405322/51185424-5edba900-18d7-11e9-82aa-5d0fe80c26ba.gif)

This happens because the linkpicker isn't geared for variant content.

Upon further inspection I've also found that:

- The anchor links selector is broken.
- The tree doesn't adhere to the main culture:
![image](https://user-images.githubusercontent.com/7405322/51185704-238daa00-18d8-11e9-8e69-504fb2dd10a7.png)

I'd go ahead and fix this but I think HQ needs to decide on how it's supposed to work first.

**Comment by nul800sebastiaan** [comment]
@kjac Yep, that would need to be the Danish names since you're editing the danish variant! 👍

**Comment by nul800sebastiaan** [comment]
@nielslyngsoe that makes sense, but it would be good to first fix it to make the default first view actually link to the language you're currently editing.

It seems like a language switcher for pickers is going to be needed soon too, but let's make that a separate feature request.

**Comment by zpqrtbnk** [comment]
you cannot link "to something in another language" - you link to another content item as a whole, not to a given culture. so, you cannot have a "danish article linking to an english article" - you have a danish article linking to another article, as a whole.

we'd need to store both the id of the picked item, and the selected culture, so that when creating the url, we create the proper url (to the proper culture)... mmm... maybe it can be done...

**Comment by nul800sebastiaan** [comment]
Fair enough! Yep it's a language variant, but obviously confusing for the editor when it's presented in "another" language. Interesting to store the culture though.. that would be quite the overhaul of all pickers I guess.

**Comment by clausjensen** [comment]
Think this was fixed and can be closed?

**Comment by kjac** [comment]
@clausjensen I don't think any work was actually done to fix this? The "[Object] object" URL is still present on the latest build:

![edit-link](https://user-images.githubusercontent.com/7405322/52713736-62c31f80-2f98-11e9-9267-7d7d937aa226.gif)

**Comment by clausjensen** [comment]
You're right - what the heck!
I must have typed and closed the wrong issue! 😱 
Reopening - sorry!

**Comment by bergmania** [comment]
The `[object Object]` URL is fixed, but none of the other discussions

**Comment by kjac** [comment]
#4507 should fix the culture issue if merged.
