### ISSUE TITLE
V.8.0.1 Multi url picker have the wrong language for content page node

### ISSUE THREAD

**Issue by filefontaine** [umbraco/Umbraco-CMS#5360]
When i select a node page in the multi url picker its select a /de/ and not a /fr/.

Reproduction
------------

### Bug summary

The multi url picker does not select the right language when the link is create. I'm editing the fr page but put a /de/ link

### Specifics

french is fallback other is English and German

### Steps to reproduce

* add an multi url picker in a node (3 languages published)
* have a multi language site (i have 3 FR-ch, EN-ch, DE-ch) with fr as default and mandatory
* have 3 languages with hostname /fr/ /de/ /en/
* try add a node page

### Expected result

a /fr/ links

### Actual result

![Screenshot_2019-04-29 Content - localhost](https://user-images.githubusercontent.com/22192319/56894108-24aca680-6a85-11e9-95ad-2dac2548627c.png)

edit : i try with a new umbraco 8.0.1 installation and the bug can be reproduced when save and published an and switch between translation and after no rollback possible

**Comment by pralthom** [comment]
Hi,

I have made some researches and I think I found where the problem is.
It is the `Umbraco.Editors.LinkPickerController` which is located in the `umbraco.controllers.js` file.

In the `nodeSelectHandler` function, `$scope.model.target.url` is set with the first value of an Array of URLs. Why the first element of the array?

![image](https://user-images.githubusercontent.com/44721265/56897985-41021080-6a90-11e9-97eb-bb8c197ed1b8.png)

**Comment by pralthom** [comment]
So we could replace the lines 1735 and 1776 by:

`$scope.model.target.url = resp.urls.filter(item => item.culture === $scope.currentNode.metaData.culture)[0].text;`

I've tested and it works fine in my testing environments.

**Comment by nul800sebastiaan** [comment]
That is cool @pralthom ! Any chance you can submit this change as a pull request so we can have a look at merging it?

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/5408

**Comment by ealse** [comment]
This bug still exists. We are working on Umbraco 8.5.3 and got still the same bug with the multi url picker.

![unnamed](https://user-images.githubusercontent.com/50272817/74639965-12fcd280-516f-11ea-91a7-c970d00651b0.png)
