### ISSUE TITLE
Styling missing for Nested Content with "min items" = 1 and "max items" = 1

### ISSUE THREAD

**Issue by jesperbrasmussen** [umbraco/Umbraco-CMS#5364]
If you create a nested content data type, and set "min items" = 1 and "max items" = 1  (first screen shot), the styling is not as pretty as if you set "min items" = 0 (second screenshot).

**EDIT: An issue if the Nested Content i nested in another Nested Content**

![MinimumOne](https://user-images.githubusercontent.com/1080053/56948668-22078b00-6b31-11e9-813f-51e6693d2876.PNG)

![MinimumZero](https://user-images.githubusercontent.com/1080053/56948666-1fa53100-6b31-11e9-877d-a91efab9fa58.PNG)

Reproduction
------------

- Create a new Nested Content data type, and set "min items" = 1 and "max items" = 1
- Nest it within another Nested Content data type.
- Add the it to a document type
- Create a document of the new document type

### Specifics

Umbraco 8.0.1
Chrome Version 73.0.3683.10
Not checked in other browsers

**Comment by kjac** [comment]
It looks like you've got your Nested Content within another Nested Content? 

It makes sense with the white background color if the Nested Content is at "root" level:

![image](https://user-images.githubusercontent.com/7405322/56955641-491a8880-6b42-11e9-8dcc-c908f3642c62.png)

I guess the background could be made transparent though, although the gray background should still be applicable for each item when multiple items are allowed... I'll have a look.

**Comment by jesperbrasmussen** [comment]
@kjac Yes your right. It is is nested within another Nested Content. That would have been relevant info in my description. I have updated the description :)

**Comment by kjac** [comment]
@jesperbrasmussen turns out... on vLatest the Nested Content styling has changed a bit, and this is solved along with it:

![image](https://user-images.githubusercontent.com/7405322/56985660-252e6580-6b89-11e9-9cab-0b0df6fcb9d2.png)

**Comment by jesperbrasmussen** [comment]
@kjac That sounds good. I upgraded to version 8.0.2 but it is not solved on that release. Are you talking about the next release?

**Comment by kjac** [comment]
@jesperbrasmussen not sure when it's released to be honest. Does your NC look anything like the screenshot above in 8.0.2?

**Comment by jesperbrasmussen** [comment]
@kjac No it looks the same. Also after doing a hard reload.

**Comment by nul800sebastiaan** [comment]
The change mentioned will be in 8.1.0. I think this issue can be closed since it will be fixed in 8.1.0 :)

**Comment by jesperbrasmussen** [comment]
@nul800sebastiaan Yes :) Thanks for the help @kjac
