### ISSUE TITLE
V8 can't "search and pick" media in 'Multi url picker'

### ISSUE THREAD

**Issue by trollsudd** [umbraco/Umbraco-CMS#5735]
When using the search function inside "select media" and pick a search result, the "Link title" is updated- but not the url = no media is picked.

Reproduction
------------

When using a "Multiple Url picker" property
1. Click on "Select media" (under heading "Link to media")
2. Search for some image/file
3. Select it with the cursor and click "Select"

If you manually navigate to the file the slection works as expected

### Bug summary

The url isn't picked up from the slected media IF its selected from a search result.

### Specifics

Umbraco v8.0.2
Chrome 75.0.3770.100
Checked in firefox 67.0.2

### Expected result

Link text and **Url** is updated with information from the slected media

### Actual result

Link text is updated
**The url is NOT updated (empty)**

**Comment by kjac** [comment]
Pretty sure this was already fixed..?

**Comment by kjac** [comment]
See https://github.com/umbraco/Umbraco-CMS/pull/5666 ... Isn't that the same issue?

**Comment by trollsudd** [comment]
> See #5666 ... Isn't that the same issue?

Yes its like #5659 but I still have the issue.

![urlpicker](https://user-images.githubusercontent.com/15833271/60267046-94a2a600-98e9-11e9-8601-0569113d6a41.gif)

**Comment by nul800sebastiaan** [comment]
Thanks @trollsudd this will be fixed in the upcoming v8.1.0.

**Comment by gmanrodt** [comment]
I still have this issue on v8.11.1. I have a JS error in the console: 
TypeError: Cannot read property 'split' of undefined
    at Object.insertLinkInEditor (umbraco.services.js?cdv=474667144:11371)

**Comment by nul800sebastiaan** [comment]
@gmanrodt I suspect that might be an upgrade or other error... seems to work on a clean install :)


https://user-images.githubusercontent.com/304656/119946103-8c03f000-bf96-11eb-8094-01ba91bbc94d.mp4
