### ISSUE TITLE
Uploading images in MediaPicker requires another step to get them selected in Umbraco 8.3

### ISSUE THREAD

**Issue by MosabAbuzaid** [umbraco/Umbraco-CMS#7293]
One of my websites that built on Umbraco 8.3 having an issue in uploading images where Users have to select images again after uploading them, which takes a lot of time.

## Umbraco version
Umbraco 8.3.0
Chrome Version 78

Reproduction
------------
1- Try to upload images , 100 images for example in any node using that has a MediaPicker property
2- After uploading them you would see them unselected
3- Then my issue will face you (select them one by one)

### Steps to reproduce
1- Try to upload images , 100 for example in any node using that has a MediaPicker property
2- After uploading them you would see them unselected
3- Then my issue will face you (select them one by one)

### Expected result
Having images selected

### Actual result
Images are getting unselected after uploading

**Comment by kjac** [comment]
Hi @MosabAbuzaid,

Thanks for reporting 👍 an annoying issue indeed.

This has also been reported in #6844 and is fixed by #6995

**Comment by MosabAbuzaid** [comment]
Hi @kjac 
thank you for replay and for fixing the problem 
i tried that and its work with media picker but unfortunately its doesn't work for rich text editor 
you have to to click on the image again to add it to rich text editor

**Comment by nul800sebastiaan** [comment]
I'll close this as a duplicate of  #6844. The fix that @kjac  mentions (#6995) is not in any Umbraco release yet so that's why the problem isn't fixed for you yet. Make sure to keep an eye on #6844 for progress on this.
