### ISSUE TITLE
Backoffice Users without access to "Settings" can't create new Members

### ISSUE THREAD

**Issue by enkelmedia** [umbraco/Umbraco-CMS#8004]
We're experiencing an issue with Umbraco 8.6 and creating new members in the Backoffice UI. This only effects users that don't have access to the "Settings"-section and it also seems like the "debug=true/false"-setting in web.config has a role in this.

## Umbraco version:
I am seeing this issue on Umbraco version: 8.6.0

Reproduction
------------
Make sure that web.config has "debug=false" set so that JS-files are bundled and minified in the backoffice.

Create a new User that has access to the "Members"-section but does not have access to the "Settings"-section and login as this User.

Go to the members-section and "Create a member", fill out required fields and click save.

After this I'm given this error:

![error message](https://user-images.githubusercontent.com/1782524/80096013-35450f00-8569-11ea-86ce-1084723b1d9e.PNG)

It's really strange but if I switch back to "debug=true" in web.config this works. I've made sure to bump the ClientDependencyVersion number so it's not a cache-issue with the client files.

### Bug summary
As far as I can tell, the "contentTypeAlias" is returned from the "GetEmpty" call to the server when the "Create new Member"-page is loaded:

![get](https://user-images.githubusercontent.com/1782524/80096782-670aa580-856a-11ea-84f9-d3ed608256bc.PNG)

But when the payload is sent to the server to be saved, the alias is no longer there:

![capture2](https://user-images.githubusercontent.com/1782524/80096797-738efe00-856a-11ea-8fe2-6754186da526.PNG)

The server side error creates the following log entry:

```
{"@t":"2020-04-23T11:45:26.7603557Z","@mt":"Unhandled controller exception occurred for request '{RequestUrl}'","@l":"Error","@x":"System.InvalidOperationException: No member type found with alias \r\n   at Umbraco.Web.Editors.Binders.MemberBinder.CreateNew(MemberSave model) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\Binders\\MemberBinder.cs:line 135\r\n   at Umbraco.Web.Editors.Binders.MemberBinder.BindModel(HttpActionContext actionContext, ModelBindingContext bindingContext) in D:\\a\\1\\s\\src\\Umbraco.Web\\Editors\\Binders\\MemberBinder.cs:line 59\r\n   at System.Web.Http.ModelBinding.ModelBinderParameterBinding.ExecuteBindingAsync(ModelMetadataProvider metadataProvider, HttpActionContext actionContext, CancellationToken cancellationToken)\r\n   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()","RequestUrl":"https://..../umbraco/backoffice/UmbracoApi/Member/PostSave","SourceContext":"Umbraco.Web.Editors.MemberController","ProcessId":12496,"ProcessName":"w3wp","ThreadId":65,"AppDomainId":20,"AppDomainAppId":"LMW3SVC76ROOT","MachineName":"OBVI-WEB","Log4NetLevel":"ERROR","HttpRequestNumber":16,"HttpRequestId":"fbf82615-4796-4e80-b882-f07270ca7d21","RequestData":"------WebKitFormBoundaryt0BjYAAZkFW5wK8D\r\nContent-Disposition: form-data; name=\"contentItem\"\r\n\r\n{\"id\":0,\"properties\":[{\"id\":0,\"alias\":\"umbracoMemberComments\",\"value\":\"\"},{\"id\":0,\"alias\":\"umbracoMemberFailedPasswordAttempts\",\"value\":\"\"},{\"id\":0,\"alias\":\"umbracoMemberApproved\",\"value\":\"1\"},{\"id\":0,\"alias\":\"umbracoMemberLockedOut\",\"value\":\"No\"},{\"id\":0,\"alias\":\"umbracoMemberLastLockoutDate\",\"value\":\"\"},{\"id\":0,\"alias\":\"umbracoMemberLastLogin\",\"value\":\"\"},{\"id\":0,\"alias\":\"umbracoMemberLastPasswordChangeDate\",\"value\":\"\"},{\"id\":0,\"alias\":\"umbracoMemberPasswordRetrievalAnswer\",\"value\":\"\"},{\"id\":0,\"alias\":\"umbracoMemberPasswordRetrievalQuestion\",\"value\":\"\"},{\"id\":0,\"alias\":\"rootNode\",\"value\":\"umb://document/9023c70aeb2149669f71a4b805a0f1ad\"}],\"name\":\"dsfsdf\",\"contentTypeAlias\":null,\"parentId\":-1,\"action\":\"saveNew\",\"key\":\"5358986b4e20448fa7424759a4e36245\",\"email\":\"...@...se\",\"username\":\"sdfsdf\",\"password\":{\"newPassword\":\"....",\"reset\":true,\"answer\":null},\"memberGroups\":[\"Företagskund\"],\"comments\":\"\",\"isApproved\":true,\"isLockedOut\":false}\r\n------WebKitFormBoundaryt0BjYAAZkFW5wK8D--\r\n"}
```

The server does not return the content-object expected so this is why we get the front end error from the "getAllProps" that is trying to iterate the tabs-property that is not present since an error was returned.

![Capture](https://user-images.githubusercontent.com/1782524/80096881-9de0bb80-856a-11ea-90d0-8aa0ef634b48.PNG)

Possible workarounds at the moment:

- Run the site with debug=true
- Give the User access to the "Settings"-section

I'm a little bit surprised that the debug-flag has any impact on this but it actually seem to have, I've tested this by bumping the clientDependencyVersionNumber and also removing all files in /App_Data/Temp/ClientDependency/* so I can't see that it's related to a cache-issue. When the User have access to the "Settings"-section the debug-mode does not matter, then it works all the time.

**Comment by enkelmedia** [comment]
I've tracked this down now,

The "umb-node-preview"-directive will change the contentTypeAlias of the content.node-object if the user is not an admin or if the sites is not in debug.

https://github.com/umbraco/Umbraco-CMS/blob/d4f84998513889351c18d988579a55397ff928fc/src/Umbraco.Web.UI.Client/src/common/directives/components/umbnodepreview.directive.js#L107

As far as I understand it, this is to prevent a editor for being able to click on a Document Type / Media Type to edit it. I guess that this directive should have a local scope for this and not change the value of the node passed into it?

**Comment by enkelmedia** [comment]
If I recall correctly I actually had an issue with a similar symptom, I've created a property editor that displayed different content depending on docType, this editor stopped to work for editors that did not have access to the settings-section - I guess the underlying cause is the same.

**Comment by enkelmedia** [comment]
I can probably provide a PR, if a local scope is the right solution for this case? 

Let me know

**Comment by nul800sebastiaan** [comment]
Wow, good find @enkelmedia! I can confirm the issue and that it's a difference between being in debug vs non-debug mode (obviously due to `Umbraco.Sys.ServerVariables.isDebuggingEnabled === true`).

I'd love to see a PR! Indeed it seems more than logical to move this to a local scope and not mess with the global one.

**Comment by ronaldbarendse** [comment]
I can confirm this issue was introduced in Umbraco 8.6.0, as our customer could create new members in 8.5.5 and that stopped working after the upgrade. We also couldn't reproduce it locally (because debug mode was on) or as admin on the live environment, making it a very hard to debug problem... This also aligns with the findings in the [comment above](https://github.com/umbraco/Umbraco-CMS/issues/8004#issuecomment-618388882).

Looks like the affected code is added in PR https://github.com/umbraco/Umbraco-CMS/pull/2692 (and documented in PR https://github.com/umbraco/Umbraco-CMS/pull/2706). I'm not sure what change in 8.6.0 caused this to be a problem though.

Besides changing the alias to a local scope, I would recommend removing the user/group check completely: the `umb-node-preview` component shouldn't have this logic. If you don't want to show the alias, you shouldn't set that property on the component. Besides, it's only used as title attribute:
https://github.com/umbraco/Umbraco-CMS/blob/044dc4eb98c419cc3911ea485aee3e44ce02d1cd/src/Umbraco.Web.UI.Client/src/views/components/umb-node-preview.html#L6

For now, there are 2 workarounds:
1. Run the site in debug mode (not recommended on a live site)
2. Add users to the admin user group (not always desirable, as customers also get access to sections they shouldn't have)

**Comment by enkelmedia** [comment]
@ronaldbarendse While I do agree, the approach that you're proposing would also mean that the fix would require changes in x number of controllers that's using this directive. I would argue that a local scope does the job without risking any side effects.

@nul800sebastiaan what way should I go with the PR?

**Comment by nul800sebastiaan** [comment]
@enkelmedia I would say go for the PR with the least amount of work necessary. 😊

**Comment by enkelmedia** [comment]
@nul800sebastiaan PR sent, its a simple fix that would be great to include in 8.7.0 =D

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8109

**Comment by remkovb** [comment]
Could it be this bug is back? We are using 8.14 and see a lot of warnings when saving member:
![image_2021_06_30T15_11_53_839Z](https://user-images.githubusercontent.com/54794463/124115986-bbfb5300-da6e-11eb-947e-5964e846d39b.png)

**Comment by enkelmedia** [comment]
@remkovb Hmm... seems more like a property editor that tries to save a string value as a int in the database.

Have a look in the "umbracoPropertyData" table in the database to try to track down what type of property that has the "Nee"-value.. it's most likely a bug in your implementation.

**Comment by ronaldbarendse** [comment]
@remkovb If you can save the member in the back-office without seeing the red notification (server error), it's definitely a different issue. Just like @enkelmedia commented, this looks more like an issue with a property editor (either in a custom implementation or because the editor was changed while still having - incompatible - data stored for that property).
