### ISSUE TITLE
Having Datepicker Show time with AM/PM

### ISSUE THREAD

**Issue by Rizen-Kris** [umbraco/Umbraco-CMS#8241]
A brief description of the issue goes here.

This is purely a back office issue:

You can change the "format" of the Date Format field in the configuration of the Date/Time Field type. It says on https://momentjs.com that "h:mm:ss a" is the format.. But it shows the calendar. It does not seem to display the picker correctly in this case..

## Umbraco version

Version: 8.6.1

Reproduction
------------
see above

### Expected result

I would expect it to popup a time editor with 3 fields Hour, Minute and am/pm
### Actual result

Shows the calendar with the time at the bottom even though the date format string only has time.

**Comment by nul800sebastiaan** [comment]
Fixed in https://github.com/umbraco/Umbraco-CMS/pull/8246

**Comment by Rizen-Kris** [comment]
This is still not 100% fixed.. the a at the end of the format "h:mm:ss a" denotes am/pm but the input still takes military time..

**Comment by davidzweben** [comment]
I wanted to bump this; this shouldn't be closed. The time picker still requires input in 24-hour format, and this provides a very poor user experience for American users who are not accustomed to thinking in 24 hour time. I have to keep translating 12-hour time to 24 hour time in my head, and this is prone to errors, and frustrating when I try to enter time as I normally do only for the UI to behave incorrectly.

There should be a settings toggle for 12-hour time that adds an AM/PM selector and has the hours roll over at 12, togging AM/PM.
