### ISSUE TITLE
Member Index does not get updated on member updates in v8.8

### ISSUE THREAD

**Issue by deekoulos** [umbraco/Umbraco-CMS#9095]
This worked fine in 8.7 but is not working anymore since updated to 8.8.

I tested this behaviour on a fresh installed solution in version 8.8, which failed. No issue in 8.7

Steps to reproduce:
Create a test member of the default member type and save
![image](https://user-images.githubusercontent.com/55948134/95263935-d5000c00-082e-11eb-9691-e3fed3a02a84.png)

Go to Settings > Examine Management > Member Index
search for the member name --> Member ist not listed
![image](https://user-images.githubusercontent.com/55948134/95264126-1f818880-082f-11eb-9d7c-14f7d81ccbb7.png)

Rebuild the member index and search again --> member gets listed
![image](https://user-images.githubusercontent.com/55948134/95264176-2f996800-082f-11eb-8395-37db0968d0ab.png)

Go to members, edit the username for the created member, save
![image](https://user-images.githubusercontent.com/55948134/95264266-4b9d0980-082f-11eb-872b-351bfbd278f5.png)

Go back to Settings > Examine > Member Index > search for the member > click on member fields
![image](https://user-images.githubusercontent.com/55948134/95264341-6f604f80-082f-11eb-8fae-4d81000210be.png)

Check the edited login name value > its not updated
![image](https://user-images.githubusercontent.com/55948134/95264414-8ef77800-082f-11eb-8738-626a694172d9.png)

Rebuild the member index, search for the member again, click on the fields >  now its updated
![image](https://user-images.githubusercontent.com/55948134/95264472-aa628300-082f-11eb-997f-7c4917997525.png)

The members index should be updated automatically on member updates.

Something happend to the members with the upgrade to 8.8, see my other bug report: https://github.com/umbraco/Umbraco-CMS/issues/9093

I retested this scenario on a fresh installed 8.7 to be sure that it worked fine there and the tests passed.

---
_This item has been added to our backlog [AB#8783](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/8783)_

**Comment by DavePearcey** [comment]
I just came here to make the same issue! I can confirm I am experiencing the same thing. Had to revert my project back to 8.7.0

**Comment by deekoulos** [comment]
@DavePearcey how did you revert the project back to 8.7? git revert or nuget downgrade? I have several feature checkins after the upgrade, so i would prefer to downgrade the package if it works, to not lose the checkins. What about db table changes, if there were some in 8.8?

**Comment by DavePearcey** [comment]
the only db change was the version number. I reverted via nuget as i also had other commited changes since. it seemed to work perfectly fine for me when i tested the revert.

**Comment by deekoulos** [comment]
big thanks Dave!!!

**Comment by deekoulos** [comment]
revert by nuget worked fine! 

i hope this gets fixed with 8.8.1 because otherwise the member index is useless completely..

**Comment by nul800sebastiaan** [comment]
I'm assuming what is causing https://github.com/umbraco/Umbraco-CMS/issues/9093 is also causing this, so I'm hopeful we'll be able to fix this with a single update. Sorry for your troubles ☹

**Comment by nul800sebastiaan** [comment]
FIxed in https://github.com/umbraco/Umbraco-CMS/pull/9146

**Comment by jattwood** [comment]
I am still seeing this issue in 8.91. Did this ever make it into 8.9.1 or is it scheduled for a later release?

**Comment by jattwood** [comment]
I am still seeing this is 8.10.1. It's affecting me because we have examine reporting based on a custom member index which never gets updated unless you manually rebuild the indexes. @nul800sebastiaan any idea if there is a workaround or what when this might be addressed??

Thanks!

**Comment by deekoulos** [comment]
@jattwood you don't need to create a custom member index. That was the issue I was also facing until I managed with the support of @nul800sebastiaan to get the built in member index to cover the requirements. 

is there any specific reason for not using the built in member index?

**Comment by jattwood** [comment]
I just have a bunch of custom member fields that’s all. Biologically went to the step of creating the custom member index. I was not aware that you can extend the existing index. Any suggestions?

Jamie Attwood

Protean Interactive
416-895-2932
________________________________

**Comment by deekoulos** [comment]
@jattwood this piece of code is all you need, to add all the custom fields to the built-in member index. I have the same scenario and its running well without issues.

you need to include Umbraco.Core for "composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();"

RegisterUnique is an extension, don't mix it with the other RegisterUnique method, which expects other parameters.

```
[RuntimeLevel(MinLevel = RuntimeLevel.Run)]
    public class ConfigureIndexComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            // replace the default IUmbracoIndexConfig definition
            composition.RegisterUnique<IUmbracoIndexConfig, CustomIndexConfig>();
        }
    }

    // inherit from the default
    public class CustomIndexConfig : UmbracoIndexConfig, IUmbracoIndexConfig
    {
        public CustomIndexConfig(IPublicAccessService publicAccessService) : base(publicAccessService)
        {
        }

        // explicit implementation - overrides base class.
        // GetMemberValueSetValidator is used for the MemberIndex.
        IValueSetValidator IUmbracoIndexConfig.GetMemberValueSetValidator()
        {
            // include everything except the above
            return new MemberValueSetValidator(null, null, null, null);
        }
    }
```

**Comment by jattwood** [comment]
Awesome Dee. Thank-you. Yeah, I just extended the U7 approach for custom fields and I guess the approach changed, which seems to be way more logical than building a whole new index.

Cheers!

**Comment by deekoulos** [comment]
awesome!

**Comment by jattwood** [comment]
We had been chatting on the forum sometime ago about this when I was suggesting custom member indexes (for U7) and then you posted one of your U8 solutions (which I am currently using) where the current index is cloned, new fields added into a new custom member index. Now we have come full circle on this, both having same bugs, both issues reported to GIT, lots of time collectively spent on this. All could be averted with better examine docs using real-life case scenarios. This needs to be front and center in the docs IMHO.

Thanks again.
