### ISSUE TITLE
Save error after validation fail

### ISSUE THREAD

**Issue by mPieczka** [umbraco/Umbraco-CMS#9341]
Hi,

I got a validation error. Document type has a text-string field with email validation (maybe with others also it will happen). A user creates this document type node in the content tab. On creating user put bad data on validate field. Umbraco returns validation error for field correctly, but after fix and press the save button again, system return 404 error. Node is saved anyway but with incorrect value (before the fix).

## Umbraco version

I see this issue on Umbraco versions: 8.8, 8.8.1 and my colleague updated 8.8 to 8.9, and it still exists.

Reproduction
------------

### Bug summary

After validation exception on creating a new node, saving returns 404 exception and saves node with incorrect filed value.

### Specifics

I think it happens on all browsers, but I have checked chrome and firefox.

![image](https://user-images.githubusercontent.com/26299040/98094979-44970480-1e8a-11eb-8525-39d4fc380436.png)
![image](https://user-images.githubusercontent.com/26299040/98095035-5aa4c500-1e8a-11eb-9998-0a763e4105e4.png)
![image](https://user-images.githubusercontent.com/26299040/98095139-76a86680-1e8a-11eb-9c8f-b17652eb723a.png)

### Steps to reproduce

1) Create new empty visual studio c# web project, and install umbraco via nuget.
2) Run the project and go through installation process.
3) Add new document type without a template, add fields group, in the group add a mandatory text-string field with email validation and validation messages. Set document type to be able as root. Save document type.
4) Go to the content tab and try to create a new node of the created document type.
5) Pass incorrect value to the field and try to save.
6) Fix value and try to save again
7) Refresh the page

### Expected result

If the validation fails, the node isn't created. After the validation fix, I can save the node.

### Actual result

After fail validation message node is created but not displayed on the content list. After page refresh, it appears. User can't fix validation issue and save a node.

---
_This item has been added to our backlog [AB#9485](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/9485)_

**Comment by nul800sebastiaan** [comment]
Thanks, I just tested this on the upcoming 8.8.2 and 8.9.1 and this is fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9215 - we hope to get those releases out early next week, apologies for the inconvenience!

**Comment by mPieczka** [comment]
Hi,

I have upgraded Umbraco version to 8.8.2, and the issue still exists. I have tried also upgrade to 8.9.1 and create new projects with those versions. In every variant, I had the same error.

**Comment by nul800sebastiaan** [comment]
Sorry about that @mPieczka it looks like I missed the fact that you were trying to validate the property as an email address, we'll have to look into it.

**Comment by nul800sebastiaan** [comment]
This is possibly a duplicate of https://github.com/umbraco/Umbraco-CMS/issues/8954

**Comment by mPieczka** [comment]
I have found a workaround for this. Adding event listener to the content saving event (https://our.umbraco.com/documentation/reference/events/ContentService-Events) and cancelling it if an email is incorrect fixes the issue. In this case, a user gets additional information about 3rd party system cancel, but it works. 

![image](https://user-images.githubusercontent.com/26299040/101329583-dcb15080-3871-11eb-8ac7-f6bf2f5b4798.png)

**Comment by nul800sebastiaan** [comment]
Apologies everyone for the delay. 

This is now fixed with PR https://github.com/umbraco/Umbraco-CMS/pull/9688 and will be available next as patch releases for 8.7 and up, plus the release of 8.11.0 also next week. 👍

**Comment by cornehoskam** [comment]
I seem to keep running into this same issue, even after upgrading to Umbraco version 8.11.1. After any kind of validation error has occurred, fixing said error does not allow for the Item to be saved, until the Item has been closed and reopened in Umbraco (and losing all changes made to it). Any idea why this may happen?
